#pragma once
#include <Arduino.h>
namespace hud { static const char ANALYSIS_JS[] PROGMEM=R"JS(
(()=>{
const style=document.createElement('style');style.textContent='.changed{background:#facc15!important;color:#111!important;border-radius:3px;padding:2px;box-shadow:0 0 8px #facc15}.handle{color:#fbbf24}.toolgrid{display:grid;grid-template-columns:repeat(auto-fit,minmax(280px,1fr));gap:10px}.bits{font:12px monospace;display:grid;grid-template-columns:repeat(8,1fr);gap:2px}.bits span{background:#183247;padding:4px;text-align:center}.alert{border-left:4px solid #ef4444}.ok{border-left:4px solid #22c55e}';document.head.append(style);
let resize=null,selectedFrameKey='',previousRaw={},byteChanges={},markers=JSON.parse(localStorage.getItem('hudMarkers')||'[]'),dbcText=localStorage.getItem('hudDbc')||'';
const tools=document.createElement('div');tools.className='toolgrid';tools.innerHTML=`<div class=card><h3>Byte / bit inspector</h3><div id=inspector class=muted>Select a frame type.</div><input id=formula placeholder="Formula, e.g. (A*256+B)/4"><button id=runFormula>Evaluate</button><output id=formulaResult></output></div><div class=card><h3>Discovery and mapping</h3><button id=discover>Supported PIDs</button> <button id=ecuMap>ECU map</button> <button id=isoTp>ISO-TP</button><div id=discovery></div></div><div class=card><h3>Correlation and events</h3><input id=corrA placeholder="7E8:0C"><input id=corrB placeholder="7E8:0D"><button id=correlate>Correlate</button><output id=corrResult></output><p><input id=markerText placeholder="Event note"><button id=addMarker>Add marker</button></p><div id=markers></div></div><div class=card><h3>Diagnostics and alerts</h3><button id=diagnostics>Refresh DTC / freeze frames</button><div id=diagList></div><div id=alerts></div></div><div class=card><h3>Import / export</h3><a href=/api/export.csv download="kia-hud-frames.csv"><button>CSV</button></a> <button id=pcapExport>PCAP</button> <button id=dbcExport>Export DBC</button><p><input id=dbcImport type=file accept=".dbc,text/plain"></p><div id=dbcState>${dbcText?'DBC loaded locally':'No DBC loaded'}</div></div>`;$('frames').append(tools);
function bytes(raw){return String(raw||'').trim().split(/\s+/).filter(Boolean).map(x=>parseInt(x,16))}
function changedBytes(key,raw){let now=bytes(raw),before=bytes(previousRaw[key]),until=byteChanges[key]||[],time=Date.now();now.forEach((v,i)=>{if(before[i]!==undefined&&before[i]!==v)until[i]=time+3000});previousRaw[key]=raw;byteChanges[key]=until;return now.map((v,i)=>`<span class="${until[i]>time?'changed':''}">${v.toString(16).padStart(2,'0').toUpperCase()}</span>`).join(' ')}
function inspect(raw){let b=bytes(raw);$('inspector').innerHTML=b.map((v,i)=>`<p><b>${String.fromCharCode(65+i)} / byte ${i}: 0x${v.toString(16).padStart(2,'0').toUpperCase()} (${v})</b></p><div class=bits>${[7,6,5,4,3,2,1,0].map(bit=>`<span>b${bit}<br>${(v>>bit)&1}</span>`).join('')}</div>`).join('')||'No bytes'}
$('runFormula').onclick=()=>{try{let b=bytes($('inspector').dataset.raw),expr=$('formula').value.trim();if(!/^[A-H0-9+\-*/%().<>&|^~ ]+$/.test(expr))throw Error('Only A-H, numbers and arithmetic/bit operators are allowed');let names='ABCDEFGH',args=names.split('').map((_,i)=>b[i]||0),v=Function(...names,`"use strict";return (${expr})`)(...args);$('formulaResult').textContent=' = '+v}catch(e){$('formulaResult').textContent=' '+e.message}};
const oldDetail=loadDetail;let detailRefreshBusy=false;loadDetail=async key=>{selectedFrameKey=key;if(detailRefreshBusy)return;detailRefreshBusy=true;try{let d=await oldDetail(key);if(!d)return;$('inspector').dataset.raw=d.raw;inspect(d.raw)}finally{detailRefreshBusy=false}};
setInterval(()=>{if(selectedFrameKey&&!selectedFrameKey.startsWith('stream:')&&!paused&&activePage==='frames')loadDetail(selectedFrameKey)},1000);
const oldLoad=loadFrames;loadFrames=async()=>{if(paused||activePage!=='frames')return;if(frameMode==='stream'){let a=await(await fetch('/api/frames?q='+encodeURIComponent($('q').value))).json();$('frameList').innerHTML=a.map((f,i)=>`<div class="frame ${selectedFrameKey==='stream:'+i?'selected':''}" data-stream="${i}" data-raw="${f.data}">${String(f.ms).padStart(10)} ${f.id} ${changedBytes('stream:'+f.id,f.data)} ${esc(f.decode||'')}</div>`).join('');$('frameState').textContent=`Live · ${a.length} frames`;$('frameList').scrollTop=$('frameList').scrollHeight;document.querySelectorAll('[data-stream]').forEach(e=>e.onclick=()=>{selectedFrameKey='stream:'+e.dataset.stream;document.querySelectorAll('.frame').forEach(row=>row.classList.toggle('selected',row===e));$('inspector').dataset.raw=e.dataset.raw;inspect(e.dataset.raw)})}else{let a=await(await fetch('/api/frame-types')).json(),query=$('q').value.toLowerCase();a=a.filter(f=>(f.key+' '+f.name+' '+f.raw).toLowerCase().includes(query)).sort((a,b)=>a.key.localeCompare(b.key));$('frameList').innerHTML=a.map(f=>`<div class="frame ${f.key===selectedFrameKey?'selected':''}" data-key="${f.key}"><b>${f.key}</b> ${esc(f.name)}<br>${changedBytes(f.key,f.raw)} · ${f.frequency.toFixed(1)} Hz</div>`).join('');$('frameState').textContent=`Locked · ${a.length} types`;document.querySelectorAll('[data-key]').forEach(e=>e.onclick=()=>{document.querySelectorAll('.frame').forEach(row=>row.classList.toggle('selected',row===e));loadDetail(e.dataset.key)});renderAlerts(a)}};
function renderAlerts(a){let bad=a.filter(f=>f.metric&&(f.min<f.realMin||f.max>f.realMax));$('alerts').innerHTML='<h4>Impossible-value alerts</h4>'+(bad.map(f=>`<p class="card alert">${esc(f.key)} ${esc(f.name)}: ${f.min}–${f.max} outside ${f.realMin}–${f.realMax} ${esc(f.unit)}</p>`).join('')||'<p class="card ok">No decoded values outside SAE ranges.</p>')}
$('discover').onclick=async()=>{let a=await(await fetch('/api/pids')).json();$('discovery').innerHTML='<h4>SAE Mode 01 PIDs</h4>'+a.filter(p=>p.supported||p.seen).map(p=>`<p><code>${p.pid}</code> ${esc(p.name)} · ${p.seen?'seen ':''}${p.supported?'supported':''} · ${p.min}–${p.max} ${esc(p.unit)}</p>`).join('')};
$('ecuMap').onclick=async()=>{let a=await(await fetch('/api/ecus')).json();$('discovery').innerHTML='<h4>ECU map</h4>'+a.map(e=>`<p><b>${esc(e.name)}</b>: ${e.frames} frames; PIDs ${e.pids.map(x=>x.toString(16).padStart(2,'0')).join(', ')}</p>`).join('')};
$('isoTp').onclick=async()=>{let a=await(await fetch('/api/isotp')).json();$('discovery').innerHTML='<h4>ISO-TP messages</h4>'+(a.map(x=>`<p>${x.id}: ${x.received}/${x.expected} bytes ${x.complete?'complete':'incomplete'}<br><code>${x.payload}</code></p>`).join('')||'<p>No multi-frame ISO-TP messages buffered.</p>')};
$('diagnostics').onclick=async()=>{let a=await(await fetch('/api/diagnostics')).json();$('diagList').innerHTML=a.map(x=>`<p class=card><b>${x.dtc}</b> · ${x.kind} · ECU ${Number(x.ecu).toString(16).toUpperCase()}</p>`).join('')||'<p>No buffered DTC responses or freeze frames.</p>'};
$('correlate').onclick=async()=>{try{let [a,b]=await Promise.all([$ ('corrA').value,$('corrB').value].map(async k=>(await(await fetch('/api/frame-detail?key='+encodeURIComponent(k))).json()).history.map(x=>x.value))),n=Math.min(a.length,b.length);if(n<3)throw Error('Need at least 3 samples for both signals');a=a.slice(-n);b=b.slice(-n);let ma=a.reduce((x,y)=>x+y)/n,mb=b.reduce((x,y)=>x+y)/n,num=0,da=0,db=0;for(let i=0;i<n;i++){let x=a[i]-ma,y=b[i]-mb;num+=x*y;da+=x*x;db+=y*y}$('corrResult').textContent=' Pearson r = '+(num/Math.sqrt(da*db)).toFixed(3)+` (${n} samples)`}catch(e){$('corrResult').textContent=' '+e.message}};
function showMarkers(){$('markers').innerHTML=markers.map((m,i)=>`<p>${new Date(m.at).toLocaleTimeString()} ${esc(m.text)} <button data-marker=${i}>×</button></p>`).join('');document.querySelectorAll('[data-marker]').forEach(b=>b.onclick=()=>{markers.splice(+b.dataset.marker,1);localStorage.setItem('hudMarkers',JSON.stringify(markers));showMarkers()})}$('addMarker').onclick=()=>{if(!$('markerText').value)return;markers.push({at:Date.now(),text:$('markerText').value});$('markerText').value='';localStorage.setItem('hudMarkers',JSON.stringify(markers));showMarkers()};showMarkers();
function download(name,type,data){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
$('pcapExport').onclick=async()=>{let a=await(await fetch('/api/frames')).json(),buf=new ArrayBuffer(24+a.length*32),v=new DataView(buf),o=0;[0xa1b2c3d4,0x00040002,0,0,65535,227].forEach(x=>{v.setUint32(o,x,true);o+=4});a.forEach(f=>{let raw=bytes(f.data),sec=Math.floor(f.ms/1000),us=(f.ms%1000)*1000;v.setUint32(o,sec,true);v.setUint32(o+4,us,true);v.setUint32(o+8,16,true);v.setUint32(o+12,16,true);v.setUint32(o+16,parseInt(f.id,16),true);v.setUint8(o+20,raw.length);raw.forEach((x,i)=>v.setUint8(o+24+i,x));o+=32});download('kia-hud.pcap','application/vnd.tcpdump.pcap',buf)};
$('dbcExport').onclick=async()=>{let a=await(await fetch('/api/frame-types')).json(),dbc='VERSION "Kia HUD generated"\n\nNS_ :\nBS_:\nBU_: HUD\n\n';a.forEach(f=>{let id=parseInt(f.key,16);dbc+=`BO_ ${id} ${f.name.replace(/\W/g,'_')}: 8 HUD\n`;if(f.metric)dbc+=` SG_ value : 0|8@1+ (1,0) [${f.realMin}|${f.realMax}] "${f.unit}" HUD\n`;dbc+='\n'});download('kia-hud.dbc','text/plain',dbc)};$('dbcImport').onchange=async e=>{dbcText=await e.target.files[0].text();localStorage.setItem('hudDbc',dbcText);$('dbcState').textContent=`Loaded ${e.target.files[0].name} (${dbcText.split(/\r?\n/).filter(x=>x.startsWith('BO_ ')).length} messages)`};
draw();loadFrames();
})();
)JS"; }
