#pragma once
#include <lvgl.h>
#include <WiFi.h>
#include <time.h>
#include <SD_MMC.h>
#include <ArduinoJson.h>
#include "Config.h"
#include "GraphicCache.h"
extern "C" { extern const lv_font_t hud_font_dejavu_16,hud_font_64,hud_font_80,hud_font_96,hud_font_128,hud_font_160,hud_font_192,hud_font_256,hud_font_320,hud_font_400; }
namespace hud {
class Dashboard {
 public:
  void setWebAccessCallback(lv_event_cb_t callback){webAccessCallback_=callback;}
  void setBeeperCallback(void(*callback)(uint32_t)){beeperCallback_=callback;}
  void begin(const DisplayState& c){root_=createRoot();populate(root_,c);}
  void rebuild(const DisplayState& c){
    oldRootPending_=root_;pendingImageBuffers_=imageBuffers_;imageBuffers_.fill(nullptr);cards_.fill(nullptr);titles_.fill(nullptr);values_.fill(nullptr);visuals_.fill(nullptr);visualKnown_.fill(false);largeEnabled_.fill(false);for(auto&chars:largeChars_)chars.fill(nullptr);for(auto&text:largeText_)text.fill(0);diagnostics_.fill({});for(auto&id:ids_)id.clear();root_=createRoot();lv_obj_add_flag(root_,LV_OBJ_FLAG_HIDDEN);populate(root_,c);
  }
  void addDiagnostics(JsonArray output)const{for(size_t i=0;i<diagnostics_.size();i++){const auto&d=diagnostics_[i];if(ids_[i].empty()||!d.redraws)continue;auto o=output.add<JsonObject>();o["slot"]=i;o["id"]=ids_[i];o["redraws"]=d.redraws;o["invalidatedPixels"]=d.invalidatedPixels;o["lastUs"]=d.lastUs;o["averageUs"]=d.averageUs;o["peakUs"]=d.peakUs;}}
  void populate(lv_obj_t* root,const DisplayState& c){for(size_t i=0;i<c.widgets.size();i++){auto&w=c.widgets[i];if(!w.visible||w.id=="webAccess")continue;cards_[i]=lv_obj_create(root);titles_[i]=lv_label_create(cards_[i]);values_[i]=lv_label_create(cards_[i]);ids_[i]=w.id;configure(i,w);}}
  void update(const DisplayState& c,const Telemetry&t,uint32_t now){
    for(size_t i=0;i<c.widgets.size();i++){
      if(!cards_[i]||!values_[i])continue;String v;auto&w=c.widgets[i];auto&id=w.id;uint8_t decimals=w.decimals==255?widgetDefaultDecimals(id):w.decimals;float raw=0;bool numeric=true,active=false;
      if(id=="speed"){raw=t.speedKph;v=String(raw,(unsigned)decimals)+(w.showUnit?" km/h":"");}else if(id=="soc"){raw=t.soc;v=String(raw,(unsigned)decimals)+(w.showUnit?" %":"");}
      else if(id=="power"||id=="rpm"){raw=t.rpm;v=String(raw,(unsigned)decimals)+(w.showUnit?" rpm":"");}else if(id=="trip"){raw=t.tripKm;v=String(raw,(unsigned)decimals)+(w.showUnit?" km":"");}
      else if(id=="coolant"){raw=t.coolantC;v=String(raw,(unsigned)decimals)+(w.showUnit?" C":"");}else if(id=="load"){raw=t.engineLoad;v=String(raw,(unsigned)decimals)+(w.showUnit?" %":"");}
      else if(id=="gpsSpeed"){raw=t.gpsSpeedKph;v=String(raw,(unsigned)decimals)+(w.showUnit?" km/h":"");}else if(id=="accel"){numeric=false;v=String(t.accelLong,(unsigned)decimals)+" / "+String(t.accelLat,(unsigned)decimals)+(w.showUnit?" g":"");}
      else if(id=="canAge"){uint32_t ageUs=micros()-t.lastCanUs;raw=ageUs/1000.0f;v=ageUs<1000?String(ageUs)+(w.showUnit?" us":""):String(raw,1)+(w.showUnit?" ms":"");}else if(id=="coordinates"){numeric=false;v=String(t.latitude,5)+", "+String(t.longitude,5);}
      else if(id=="status"){numeric=false;active=now-t.lastCanMs<1000;v=String(t.gpsFix?"GPS fix | ":"GPS -- | ")+String(now-t.lastCanMs)+"ms";}
      else if(id=="version"){numeric=false;v=FIRMWARE_VERSION;}else if(id=="gpsLock"){numeric=false;active=t.gpsFix;v=t.gpsFix?"LOCKED":"NO FIX";}
      else if(id=="uptime"){numeric=false;v=String(now/1000)+" s";}else if(id=="wifi"){numeric=false;active=WiFi.status()==WL_CONNECTED;v=active?WiFi.localIP().toString():"offline";}else if(id=="battery"){numeric=false;active=t.batteryPower;v=t.batteryPower?"BATTERY BACKUP":"EXTERNAL POWER";}
      else if(id=="intakeTemp"){raw=t.intakeTempC;v=String(raw,(unsigned)decimals)+(w.showUnit?" C":"");}else if(id=="throttle"){raw=t.throttlePct;v=String(raw,(unsigned)decimals)+(w.showUnit?" %":"");}
      else if(id=="voltage"){raw=t.controlVoltage;v=String(raw,(unsigned)decimals)+(w.showUnit?" V":"");}else if(id=="ambientTemp"){raw=t.ambientTempC;v=String(raw,(unsigned)decimals)+(w.showUnit?" C":"");}
      else if(id=="fuelRate"){raw=t.fuelRateLph;v=String(raw,(unsigned)decimals)+(w.showUnit?" L/h":"");}else if(id=="wifiSignal"){raw=WiFi.status()==WL_CONNECTED?WiFi.RSSI():-100;v=WiFi.status()==WL_CONNECTED?String((int)raw)+(w.showUnit?" dBm":""):"offline";}
      else if(id=="mode"){numeric=false;active=true;v=c.simulateObd?"SIMULATION":c.canListenOnly?"CAN LISTEN":"OBD POLLING";}else if(id=="webAccess"){numeric=false;active=true;v="Tap to connect";}else if(id=="text"){numeric=false;v=w.title;}
      else if(id=="time"||id=="date"){numeric=false;time_t epoch=time(nullptr);if(epoch>1700000000){struct tm local;localtime_r(&epoch,&local);char text[24];const char*formats[]={"%H:%M:%S","%H:%M","%I:%M:%S %p","%I:%M %p"};strftime(text,sizeof(text),id=="time"?formats[min((uint8_t)3,w.timeFormat)]:"%Y-%m-%d",&local);v=text;}else v="--";}else{numeric=false;v="--";}
      auto value=values_[i];bool textChanged=largeEnabled_[i]?strcmp(largeText_[i].data(),v.c_str())!=0:strcmp(lv_label_get_text(value),v.c_str())!=0;bool visualChanged=w.visualStyle!=WIDGET_VALUE&&(!visualKnown_[i]||fabsf(raw-lastVisual_[i])>.0001f||active!=lastActive_[i]);uint32_t started=(textChanged||visualChanged)?micros():0,invalidated=0;if(textChanged){if(largeEnabled_[i])invalidated=updateLargeValue(i,w,v);else{lv_label_set_text(value,v.c_str());invalidated=(uint32_t)w.w*w.h;if(!usesMetricGlyphs(w)){lv_obj_update_layout(value);alignValue(value,w);lv_obj_refresh_ext_draw_size(value);}}}if(visualChanged){applyVisual(i,w,raw,numeric,active);lastVisual_[i]=raw;lastActive_[i]=active;visualKnown_[i]=true;invalidated=max(invalidated,(uint32_t)w.w*w.h);}if(started){uint32_t elapsed=micros()-started;auto&d=diagnostics_[i];d.redraws++;d.invalidatedPixels+=invalidated;d.lastUs=elapsed;d.averageUs=d.averageUs?d.averageUs*.9f+elapsed*.1f:elapsed;d.peakUs=max(d.peakUs,(float)elapsed);}bool alarm=w.beepEnabled&&numeric&&((w.beepWhen==1&&raw>w.beepThreshold)||(w.beepWhen==2&&raw<w.beepThreshold));if(alarm&&beeperCallback_&&(!lastBeepMs_[i]||now-lastBeepMs_[i]>=w.beepTimeoutMs)){lastBeepMs_[i]=now;beeperCallback_(180);}
    }
    if(oldRootPending_){lv_obj_update_layout(root_);lv_obj_clear_flag(root_,LV_OBJ_FLAG_HIDDEN);lv_obj_del(oldRootPending_);oldRootPending_=nullptr;for(auto*buffer:pendingImageBuffers_)if(buffer)free(buffer);pendingImageBuffers_.fill(nullptr);}
  }
  void sendToBack(){if(root_)lv_obj_move_background(root_);}
 private:
  static bool usesMetricGlyphs(const Widget&w){auto&id=w.id;return id=="speed"||id=="soc"||id=="power"||id=="rpm"||id=="trip"||id=="coolant"||id=="load"||id=="gpsSpeed"||id=="accel"||id=="canAge"||id=="intakeTemp"||id=="throttle"||id=="voltage"||id=="ambientTemp"||id=="fuelRate"||id=="wifiSignal";}
  static const lv_font_t* fontFor(const Widget&w){if(w.fontSize>48){if(w.fontSize>=360)return &hud_font_400;if(w.fontSize>=288)return &hud_font_320;if(w.fontSize>=224)return &hud_font_256;if(w.fontSize>=176)return &hud_font_192;if(w.fontSize>=144)return &hud_font_160;if(w.fontSize>=112)return &hud_font_128;if(w.fontSize>=88)return &hud_font_96;if(w.fontSize>=72)return &hud_font_80;return &hud_font_64;}if(w.fontFamily==1)return &lv_font_unscii_16;if(w.fontFamily==2)return &hud_font_dejavu_16;if(w.fontSize>=45)return &lv_font_montserrat_48;if(w.fontSize>=40)return &lv_font_montserrat_42;if(w.fontSize>=36)return &lv_font_montserrat_38;if(w.fontSize>=32)return &lv_font_montserrat_34;if(w.fontSize>=28)return &lv_font_montserrat_30;if(w.fontSize>=24)return &lv_font_montserrat_26;if(w.fontSize>=20)return &lv_font_montserrat_22;if(w.fontSize>=18)return &lv_font_montserrat_18;if(w.fontSize>=16)return &lv_font_montserrat_16;if(w.fontSize>=14)return &lv_font_montserrat_14;if(w.fontSize>=12)return &lv_font_montserrat_12;return &lv_font_montserrat_10;}
  static uint16_t fontBaseSize(const Widget&w){if(w.fontSize>48){return w.fontSize>=360?400:w.fontSize>=288?320:w.fontSize>=224?256:w.fontSize>=176?192:w.fontSize>=144?160:w.fontSize>=112?128:w.fontSize>=88?96:w.fontSize>=72?80:64;}if(w.fontFamily)return 16;return w.fontSize>=45?48:w.fontSize>=40?42:w.fontSize>=36?38:w.fontSize>=32?34:w.fontSize>=28?30:w.fontSize>=24?26:w.fontSize>=20?22:w.fontSize>=18?18:w.fontSize>=16?16:w.fontSize>=14?14:w.fontSize>=12?12:10;}
  static void alignValue(lv_obj_t*value,const Widget&w){if(w.visualStyle==WIDGET_BAR)lv_obj_align(value,LV_ALIGN_CENTER,0,-3);else if(w.visualStyle==WIDGET_GAUGE)lv_obj_align(value,LV_ALIGN_CENTER,0,8);else if(w.visualStyle==WIDGET_LIGHT)lv_obj_align(value,LV_ALIGN_CENTER,14,8);else lv_obj_align(value,w.valueAlign==0?LV_ALIGN_LEFT_MID:w.valueAlign==2?LV_ALIGN_RIGHT_MID:LV_ALIGN_CENTER,0,8);}
  uint32_t updateLargeValue(size_t i,const Widget&w,const String&value){constexpr size_t LIMIT=20;auto font=fontFor(w);size_t oldLength=strlen(largeText_[i].data()),length=min(value.length(),LIMIT-1);bool relayout=oldLength!=length;uint16_t digitWidth=0;for(char digit='0';digit<='9';digit++){char text[2]={digit,0};digitWidth=max(digitWidth,(uint16_t)lv_txt_get_width(text,1,font,0,LV_TEXT_FLAG_NONE));}uint16_t widths[LIMIT]={};uint32_t total=0;for(size_t n=0;n<length;n++){char text[2]={value[n],0};widths[n]=isdigit((unsigned char)value[n])?digitWidth:(uint16_t)lv_txt_get_width(text,1,font,0,LV_TEXT_FLAG_NONE);total+=widths[n];}int x=w.valueAlign==0?8:w.valueAlign==2?w.w-8-(int)total:((int)w.w-(int)total)/2,y=((int)w.h-font->line_height)/2+8;uint32_t invalidated=relayout?(uint32_t)w.w*w.h:0;for(size_t n=0;n<LIMIT;n++){auto&label=largeChars_[i][n];if(n>=length){if(label&&!lv_obj_has_flag(label,LV_OBJ_FLAG_HIDDEN)){lv_obj_add_flag(label,LV_OBJ_FLAG_HIDDEN);invalidated+=(uint32_t)digitWidth*font->line_height;}continue;}if(!label){label=lv_label_create(cards_[i]);lv_obj_set_style_text_color(label,lv_color_hex(w.textColor),0);lv_obj_set_style_text_font(label,font,0);lv_label_set_long_mode(label,LV_LABEL_LONG_CLIP);relayout=true;}char text[2]={value[n],0};if(strcmp(lv_label_get_text(label),text)){lv_label_set_text(label,text);invalidated+=(uint32_t)max(widths[n],digitWidth)*font->line_height;}lv_obj_clear_flag(label,LV_OBJ_FLAG_HIDDEN);if(relayout){lv_obj_set_size(label,widths[n]+2,font->line_height+4);lv_obj_set_pos(label,x,y);}x+=widths[n];}memcpy(largeText_[i].data(),value.c_str(),length);largeText_[i][length]=0;return invalidated;}
  void createIcon(size_t i,const Widget&w,lv_obj_t*card){uint16_t width=0,height=0;uint8_t*buffer=nullptr;String resource=w.resource[0]?w.resource:"builtin:info";File f;if(graphic_cache::resourcePath(resource)&&SD_MMC.cardType()!=CARD_NONE)f=SD_MMC.open(resource,"r");if(!f&&graphic_cache::resourcePath(resource))graphic_cache::open(resource,f);size_t bytes=0;if(f&&graphic_cache::validRgb565(f,width,height,bytes)){f.seek(4);buffer=(uint8_t*)heap_caps_malloc(bytes,MALLOC_CAP_SPIRAM);if(buffer&&f.read(buffer,bytes)!=bytes){free(buffer);buffer=nullptr;}}if(f)f.close();if(!buffer){width=min((int)w.w-16,160);height=min((int)w.h-16,160);size_t pixels=(size_t)width*height;buffer=(uint8_t*)heap_caps_malloc(pixels*2,MALLOC_CAP_SPIRAM);if(!buffer)return;uint16_t*px=(uint16_t*)buffer,bg=lv_color_hex(w.background).full,fg=lv_color_hex(resource.indexOf("warning")>=0||resource.indexOf("temperature")>=0?0xef4444:resource.indexOf("battery")>=0?0xfbbf24:resource.indexOf("check")>=0?0x22c55e:0x2dd4bf).full;for(size_t n=0;n<pixels;n++)px[n]=bg;int cx=width/2,cy=height/2,r=min(width,height)/2-3;for(int y=0;y<height;y++)for(int x=0;x<width;x++){int dx=x-cx,dy=y-cy;bool mark=resource.indexOf("warning")>=0?(y>height/8&&abs(dx)<(y-height/8)/2):dx*dx+dy*dy<r*r;if(mark)px[y*width+x]=fg;}}imageBuffers_[i]=buffer;auto&d=imageDescriptors_[i];memset(&d,0,sizeof(d));d.header.w=width;d.header.h=height;d.header.cf=LV_IMG_CF_TRUE_COLOR;d.data_size=(uint32_t)width*height*2;d.data=buffer;visuals_[i]=lv_img_create(card);lv_img_set_src(visuals_[i],&d);lv_obj_align(visuals_[i],LV_ALIGN_CENTER,0,0);}
  void configure(size_t i,const Widget&w){
    auto card=cards_[i];lv_obj_set_pos(card,w.x,w.y);lv_obj_set_size(card,w.w,w.h);lv_obj_clear_flag(card,LV_OBJ_FLAG_OVERFLOW_VISIBLE);lv_obj_set_style_bg_color(card,lv_color_hex(w.background),0);lv_obj_set_style_bg_opa(card,w.backgroundOpacity,0);lv_obj_set_style_border_color(card,lv_color_hex(0x2dd4bf),0);lv_obj_set_style_border_width(card,w.border?2:0,0);lv_obj_set_style_radius(card,10,0);lv_obj_clear_flag(card,LV_OBJ_FLAG_SCROLLABLE|LV_OBJ_FLAG_CLICKABLE);if(webAccessCallback_)lv_obj_remove_event_cb(card,webAccessCallback_);if(w.id=="webAccess"&&webAccessCallback_){lv_obj_add_flag(card,LV_OBJ_FLAG_CLICKABLE);lv_obj_add_event_cb(card,webAccessCallback_,LV_EVENT_CLICKED,nullptr);}
    auto title=titles_[i];lv_label_set_text(title,w.id=="text"?"":w.title);lv_obj_set_style_text_color(title,lv_color_hex(w.textColor),0);lv_obj_align(title,LV_ALIGN_TOP_LEFT,0,0);
    auto value=values_[i];lv_obj_set_style_text_color(value,lv_color_hex(w.textColor),0);lv_obj_set_style_text_font(value,fontFor(w),0);lv_obj_set_style_transform_zoom(value,256,0);lv_obj_set_style_transform_pivot_x(value,lv_pct(50),0);lv_obj_set_style_transform_pivot_y(value,lv_pct(50),0);lv_obj_clear_flag(value,LV_OBJ_FLAG_OVERFLOW_VISIBLE|LV_OBJ_FLAG_HIDDEN);largeEnabled_[i]=w.fontSize>=64&&usesMetricGlyphs(w)&&w.visualStyle==WIDGET_VALUE;if(largeEnabled_[i])lv_obj_add_flag(value,LV_OBJ_FLAG_HIDDEN);
    if(visuals_[i]){lv_obj_del(visuals_[i]);visuals_[i]=nullptr;}
    if(w.id=="icon"){lv_obj_add_flag(value,LV_OBJ_FLAG_HIDDEN);createIcon(i,w,card);}
    else if(w.visualStyle==WIDGET_BAR){visuals_[i]=lv_bar_create(card);lv_obj_set_size(visuals_[i],max(20,w.w-24),w.visualThickness);lv_obj_align(visuals_[i],LV_ALIGN_BOTTOM_MID,0,-5);lv_bar_set_range(visuals_[i],0,1000);lv_obj_set_style_bg_color(visuals_[i],lv_color_hex(w.trackColor),LV_PART_MAIN);lv_obj_set_style_bg_color(visuals_[i],lv_color_hex(w.accentColor),LV_PART_INDICATOR);lv_obj_align(value,LV_ALIGN_CENTER,0,-3);}
    else if(w.visualStyle==WIDGET_GAUGE){int size=max(30,min(w.w-20,w.h-28));visuals_[i]=lv_arc_create(card);lv_obj_set_size(visuals_[i],size,size);lv_obj_align(visuals_[i],LV_ALIGN_CENTER,0,8);lv_arc_set_range(visuals_[i],0,1000);lv_arc_set_bg_angles(visuals_[i],135,45);lv_obj_remove_style(visuals_[i],nullptr,LV_PART_KNOB);lv_obj_clear_flag(visuals_[i],LV_OBJ_FLAG_CLICKABLE);lv_obj_set_style_arc_color(visuals_[i],lv_color_hex(w.trackColor),LV_PART_MAIN);lv_obj_set_style_arc_color(visuals_[i],lv_color_hex(w.accentColor),LV_PART_INDICATOR);lv_obj_set_style_arc_width(visuals_[i],w.visualThickness,LV_PART_MAIN);lv_obj_set_style_arc_width(visuals_[i],w.visualThickness,LV_PART_INDICATOR);lv_obj_align(value,LV_ALIGN_CENTER,0,8);lv_obj_move_foreground(value);}
    else if(w.visualStyle==WIDGET_LIGHT){visuals_[i]=lv_obj_create(card);int diameter=min(48,max(12,(int)w.visualThickness*3));lv_obj_set_size(visuals_[i],diameter,diameter);lv_obj_set_style_radius(visuals_[i],LV_RADIUS_CIRCLE,0);lv_obj_set_style_border_width(visuals_[i],0,0);lv_obj_align(visuals_[i],LV_ALIGN_LEFT_MID,4,8);lv_obj_align(value,LV_ALIGN_CENTER,14,8);}
    else alignValue(value,w);
    lv_obj_move_foreground(card);
  }
  void applyVisual(size_t i,const Widget&w,float raw,bool numeric,bool active){if(!visuals_[i])return;float lo=0,hi=1;bool ranged=numeric&&widgetVisualRange(w,lo,hi);int level=ranged?(int)constrain((raw-lo)*1000.0f/(hi-lo),0.0f,1000.0f):(active?1000:0);if(w.visualStyle==WIDGET_BAR)lv_bar_set_value(visuals_[i],level,LV_ANIM_OFF);else if(w.visualStyle==WIDGET_GAUGE)lv_arc_set_value(visuals_[i],level);else if(w.visualStyle==WIDGET_LIGHT){float low,high;widgetLightLimits(w,lo,hi,low,high);uint32_t color=raw>=high?w.highColor:raw>=low?w.midColor:w.lowColor;if(!numeric)color=active?w.highColor:w.lowColor;lv_obj_set_style_bg_color(visuals_[i],lv_color_hex(color),0);lv_obj_set_style_shadow_color(visuals_[i],lv_color_hex(color),0);lv_obj_set_style_shadow_width(visuals_[i],w.visualThickness,0);}}
  static lv_obj_t* createRoot(){auto root=lv_obj_create(lv_scr_act());lv_obj_set_size(root,480,480);lv_obj_set_pos(root,0,0);lv_obj_set_style_bg_color(root,lv_color_hex(0x071018),0);lv_obj_set_style_border_width(root,0,0);lv_obj_set_style_pad_all(root,0,0);lv_obj_clear_flag(root,LV_OBJ_FLAG_SCROLLABLE);lv_obj_add_flag(root,LV_OBJ_FLAG_OVERFLOW_VISIBLE);return root;}
  struct RenderDiagnostic{uint32_t redraws=0;uint64_t invalidatedPixels=0;float lastUs=0,averageUs=0,peakUs=0;};lv_obj_t*root_=nullptr;lv_obj_t*oldRootPending_=nullptr;std::array<lv_obj_t*,40>cards_{};std::array<lv_obj_t*,40>titles_{};std::array<lv_obj_t*,40>values_{};std::array<lv_obj_t*,40>visuals_{};std::array<std::array<lv_obj_t*,20>,40>largeChars_{};std::array<std::array<char,20>,40>largeText_{};std::array<std::string,40>ids_{};std::array<uint32_t,40>lastBeepMs_{};std::array<float,40>lastVisual_{};std::array<bool,40>lastActive_{},visualKnown_{},largeEnabled_{};std::array<RenderDiagnostic,40>diagnostics_{};std::array<uint8_t*,40>imageBuffers_{},pendingImageBuffers_{};std::array<lv_img_dsc_t,40>imageDescriptors_{};lv_event_cb_t webAccessCallback_=nullptr;void(*beeperCallback_)(uint32_t)=nullptr;
};}
