[platformio]
src_dir = firmware/KiaXCeedHUD
include_dir = firmware/KiaXCeedHUD/src

[env:waveshare-esp32-s3-touch-lcd-4]
platform = espressif32@6.10.0
board = esp32-s3-devkitc-1
framework = arduino
board_build.flash_size = 16MB
board_build.psram_type = opi
board_build.arduino.memory_type = qio_opi
board_build.partitions = default_16MB.csv
build_flags =
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DCORE_DEBUG_LEVEL=1
  -DLV_CONF_INCLUDE_SIMPLE
lib_deps =
  lvgl/lvgl@^8.3.11
  moononournation/GFX Library for Arduino@^1.5.0
  lewisxhe/SensorLib@^0.3.1
  bblanchon/ArduinoJson@^7.2.1
  esp32async/ESPAsyncWebServer@^3.7.7
  esp32async/AsyncTCP@^3.3.2
monitor_speed = 115200
