#include <Arduino.h>
#include <new>
#include <WiFi.h>
#include <ESPAsyncWebServer.h>
#include <ArduinoJson.h>
#include <DNSServer.h>
#include <qrcode.h>
#include <ESPmDNS.h>
#include <ArduinoOTA.h>
#include <esp_system.h>
#include <lvgl.h>
#include <time.h>
#include "src/Core.h"
#include "src/Config.h"
#include "src/VehicleBus.h"
#include "src/WebUi.h"
#include "src/Display.h"
#include "src/TestMode.h"
#include "src/OtaUi.h"
#include "src/Dashboard.h"
#include "src/ObdSimulator.h"
#include "src/AnalysisUi.h"
#include "src/Performance.h"
#include "src/BoardServices.h"
#include "src/FrameAnalytics.h"
#include "src/GraphicCache.h"

using namespace hud;
Config* cfgStorage=nullptr;
#define cfg (*cfgStorage)
DisplayState displayCfg; VehicleBus bus; Telemetry telemetry; TemporaryAccess accessGate;
AsyncWebServer server(80); AsyncEventSource events("/api/events"); DNSServer dns; DisplayPort display; Dashboard dashboard;
BoardServices boardServices;
volatile bool boardServicesReady=false;
volatile bool splashCacheRefreshRequested=true;
static void triggerBeeper(uint32_t durationMs){if(boardServicesReady)boardServices.beep(durationMs);}
static void initBoardServices(void*){boardServices.begin();boardServicesReady=true;Serial.printf("Board services: SD %s (%s, attempts %u, %u kHz, type %u, %llu bytes, writable %s), battery IC %s, buzzer %s\n",boardServices.sdMounted()?"mounted":"unavailable",boardServices.sdStage(),boardServices.sdAttempts(),(unsigned)boardServices.sdFrequencyKhz(),boardServices.sdCardType(),(unsigned long long)boardServices.sdCardSize(),boardServices.sdWritable()?"yes":"no",boardServices.batteryPresent()?"detected":"unavailable",boardServices.buzzerPresent()?"ready":"unavailable");vTaskDelete(nullptr);}
PerformanceMonitor* performance=nullptr;
CanFrame* frames=nullptr;size_t frameCapacity=0,frameHead=0,frameCount=0;
FrameAnalytics* frameAnalytics=nullptr;SemaphoreHandle_t frameAnalyticsMutex=nullptr;
uint32_t frameTotal=0,qrShownAt=0;
lv_obj_t *accessLabel,*armButton,*qrCanvas,*qrBackdrop;
lv_color_t* qrPixels=nullptr; String apSsid,apPassword;
volatile bool stopWebRequested=false;
bool mdnsStarted=false;
bool displayStarted=false;
bool otaConnecting=false,otaStarted=false;uint32_t otaDeadline=0;String otaUploadPassword;
volatile bool otaStartRequested=false;
volatile uint32_t displayConfigRequested=1;
uint32_t displayConfigApplied=0;
SemaphoreHandle_t configMutex=nullptr;
int8_t activeVirtualDisplay=-1;uint32_t bootDisplayUntil=0;bool batteryPowerActive=false;
static void initWifi();
static CanFrame&frameAt(size_t n){return frames[(frameHead+frameCapacity-frameCount+n)%frameCapacity];}
static void recordFrame(const CanFrame&f){if(!frames||!frameCapacity)return;while(frameCount&&f.ms-frameAt(0).ms>FRAME_HISTORY_MS)frameCount--;if(frameCount==frameCapacity){frameCount--;performance->noteCanCoalesced();}frames[frameHead]=f;frameHead=(frameHead+1)%frameCapacity;frameCount++;if(frameAnalytics&&frameAnalyticsMutex){if(xSemaphoreTake(frameAnalyticsMutex,0)==pdTRUE){uint32_t started=micros();frameAnalytics->record(f);xSemaphoreGive(frameAnalyticsMutex);performance->recordAnalysis(micros()-started);}else performance->noteCanCoalesced();}}
static void selectDisplay(int8_t index){displayCfg.simulateObd=cfg.simulateObd;displayCfg.canListenOnly=cfg.canListenOnly;displayCfg.brightness=cfg.brightness;displayCfg.widgets=index>=0?cfg.virtualDisplays[index].widgets:cfg.widgets;}
static uint32_t activeDisplayFingerprint(const Config& value){JsonDocument j;j["brightness"]=value.brightness;j["simulateObd"]=value.simulateObd;j["canListenOnly"]=value.canListenOnly;auto a=j["widgets"].to<JsonArray>();if(activeVirtualDisplay>=0&&activeVirtualDisplay<(int8_t)value.virtualDisplays.size())Config::widgetsToJson(a,value.virtualDisplays[activeVirtualDisplay].widgets);else Config::widgetsToJson(a,value.widgets);String encoded;serializeJson(j,encoded);uint32_t hash=2166136261u;for(size_t i=0;i<encoded.length();i++){hash^=(uint8_t)encoded[i];hash*=16777619u;}return hash;}
static bool vehicleMoving(){return !cfg.simulateObd&&max(telemetry.speedKph,telemetry.gpsSpeedKph)>=1.0f;}
static float conditionMetric(const char*metric){if(!strcmp(metric,"speed"))return telemetry.speedKph;if(!strcmp(metric,"rpm"))return telemetry.rpm;if(!strcmp(metric,"coolant"))return telemetry.coolantC;if(!strcmp(metric,"soc"))return telemetry.soc;if(!strcmp(metric,"load"))return telemetry.engineLoad;if(!strcmp(metric,"voltage"))return telemetry.controlVoltage;return 0;}
static bool displayCondition(const VirtualDisplay&d){if(!d.enabled)return false;if(d.condition==CONDITION_BOOT)return (int32_t)(bootDisplayUntil-millis())>0;if(d.condition==CONDITION_BATTERY)return batteryPowerActive;float value=conditionMetric(d.metric);switch(d.condition){case CONDITION_LT:return value<d.threshold;case CONDITION_LTE:return value<=d.threshold;case CONDITION_GT:return value>d.threshold;case CONDITION_GTE:return value>=d.threshold;case CONDITION_EQ:return fabsf(value-d.threshold)<0.01f;default:return false;}}
static int8_t desiredVirtualDisplay(){for(int i=(int)cfg.virtualDisplays.size()-1;i>=0;i--)if(displayCondition(cfg.virtualDisplays[i]))return i;return -1;}
static String splashGraphicResource(){for(const auto&w:cfg.virtualDisplays[0].widgets)if(w.visible&&w.id=="icon"&&graphic_cache::resourcePath(w.resource))return w.resource;return "";}
static void refreshSplashCache(){String resource=splashGraphicResource();if(!resource.length())return;bool refreshed=graphic_cache::refresh(resource);Serial.printf("Splash graphic cache: %s (%s)\n",refreshed?"updated":"unchanged",resource.c_str());}

static bool fromTestLan(AsyncWebServerRequest*r){return test_mode::enabled&&WiFi.status()==WL_CONNECTED&&r->client()->localIP()==WiFi.localIP();}
static uint32_t clientId(AsyncWebServerRequest*r){if(r->client()->localIP()!=WiFi.softAPIP())return 0;return (uint32_t)r->client()->remoteIP();}
static bool auth(AsyncWebServerRequest*r){if(fromTestLan(r)||accessGate.authorized(millis(),clientId(r)))return true;r->send(401,"application/json","{\"error\":\"unauthorized\"}");return false;}
static void sendJson(AsyncWebServerRequest*r,JsonDocument&d){String s;serializeJson(d,s);r->send(200,"application/json",s);performance->webEnd(r);}
static bool requestAuthorized(AsyncWebServerRequest*r){return fromTestLan(r)||accessGate.authorized(millis(),clientId(r));}
static bool sdPath(const String&input,String&output,bool allowRoot=true){if(!input.length()||input[0]!='/'||input.length()>240||input.indexOf("\\")>=0||input.indexOf("..")>=0)return false;output="";bool slash=false;for(size_t i=0;i<input.length();i++){char c=input[i];if((uint8_t)c<32||c==127)return false;if(c=='/'){if(slash)continue;slash=true;}else slash=false;output+=c;}while(output.length()>1&&output.endsWith("/"))output.remove(output.length()-1);return allowRoot||output!="/";}
static String sdBaseName(const String&path){int slash=path.lastIndexOf('/');return slash>=0?path.substring(slash+1):path;}
static void sdError(AsyncWebServerRequest*r,int status,const char*message){JsonDocument j;j["error"]=message;String body;serializeJson(j,body);r->send(status,"application/json",body);performance->webEnd(r);}

static String randomSecret(size_t length){static const char alphabet[]="ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789";String s;s.reserve(length);for(size_t i=0;i<length;i++)s+=alphabet[esp_random()%(sizeof(alphabet)-1)];return s;}
static void startOta(lv_event_t*){if(!cfg.otaSsid.length()||!cfg.otaPassword.length()){lv_label_set_text(accessLabel,"Configure hotspot credentials in the web UI first");lv_obj_clear_flag(accessLabel,LV_OBJ_FLAG_HIDDEN);return;}if(vehicleMoving()){lv_label_set_text(accessLabel,"OTA refused while vehicle is moving");lv_obj_clear_flag(accessLabel,LV_OBJ_FLAG_HIDDEN);return;}otaUploadPassword=randomSecret(20);otaDeadline=millis()+600000;otaConnecting=true;otaStarted=false;MDNS.end();mdnsStarted=false;WiFi.mode(WIFI_STA);WiFi.begin(cfg.otaSsid,cfg.otaPassword);lv_label_set_text_fmt(accessLabel,"OTA: connecting to %s...",cfg.otaSsid.c_str());lv_obj_clear_flag(accessLabel,LV_OBJ_FLAG_HIDDEN);}
static void stopOta(const char* reason){if(otaStarted)ArduinoOTA.end();otaStarted=otaConnecting=false;otaDeadline=0;otaUploadPassword="";lv_label_set_text(accessLabel,reason);lv_obj_clear_flag(accessLabel,LV_OBJ_FLAG_HIDDEN);initWifi();}
static void updateOta(){if(!otaConnecting&&!otaStarted)return;if(vehicleMoving()){stopOta("OTA cancelled: vehicle moving");return;}if((int32_t)(millis()-otaDeadline)>=0){stopOta("OTA window expired");return;}if(otaConnecting&&WiFi.status()==WL_CONNECTED){ArduinoOTA.setHostname("kia-hud-ota");ArduinoOTA.setPassword(otaUploadPassword.c_str());ArduinoOTA.onStart([](){lv_label_set_text(accessLabel,"OTA update started - do not remove power");});ArduinoOTA.onProgress([](unsigned int done,unsigned int total){lv_label_set_text_fmt(accessLabel,"OTA updating: %u%%",total?done*100/total:0);});ArduinoOTA.onEnd([](){lv_label_set_text(accessLabel,"OTA complete - rebooting");});ArduinoOTA.onError([](ota_error_t error){lv_label_set_text_fmt(accessLabel,"OTA error %u",error);});ArduinoOTA.begin();otaConnecting=false;otaStarted=true;lv_label_set_text_fmt(accessLabel,"OTA READY (10 minutes)\nHost: kia-hud-ota.local\nIP: %s\nPassword: %s",WiFi.localIP().toString().c_str(),otaUploadPassword.c_str());}if(otaStarted)ArduinoOTA.handle();}
static void renderQr(esp_qrcode_handle_t qr){const int quiet=4,size=esp_qrcode_get_size(qr),scale=max(1,440/(size+quiet*2)),side=(size+quiet*2)*scale;if(!qrPixels)qrPixels=(lv_color_t*)heap_caps_malloc(440*440*sizeof(lv_color_t),MALLOC_CAP_SPIRAM);lv_canvas_set_buffer(qrCanvas,qrPixels,side,side,LV_IMG_CF_TRUE_COLOR);lv_canvas_fill_bg(qrCanvas,lv_color_white(),LV_OPA_COVER);for(int y=0;y<size;y++)for(int x=0;x<size;x++)if(esp_qrcode_get_module(qr,x,y))for(int py=0;py<scale;py++)for(int px=0;px<scale;px++)lv_canvas_set_px_color(qrCanvas,(x+quiet)*scale+px,(y+quiet)*scale+py,lv_color_black());lv_obj_clear_flag(qrCanvas,LV_OBJ_FLAG_HIDDEN);}
static void showQr(const String& text){esp_qrcode_config_t q={renderQr,5,ESP_QRCODE_ECC_LOW};esp_qrcode_generate(&q,text.c_str());}
static void hideQr(lv_event_t*){qrShownAt=0;if(qrBackdrop)lv_obj_add_flag(qrBackdrop,LV_OBJ_FLAG_HIDDEN);lv_obj_add_flag(qrCanvas,LV_OBJ_FLAG_HIDDEN);lv_obj_add_flag(accessLabel,LV_OBJ_FLAG_HIDDEN);}
static void stopWeb(){dns.stop();WiFi.softAPdisconnect(true);accessGate.revoke();apPassword="";apSsid="";hideQr(nullptr);WiFi.mode(WIFI_STA);if(test_mode::enabled)WiFi.begin(test_mode::ssid,test_mode::password);else if(!cfg.ssid.length())WiFi.disconnect(false,false);}
static void presentQr(const String&payload,const String&message){showQr(payload);qrShownAt=millis();lv_label_set_text(accessLabel,message.c_str());lv_obj_clear_flag(qrBackdrop,LV_OBJ_FLAG_HIDDEN);lv_obj_clear_flag(accessLabel,LV_OBJ_FLAG_HIDDEN);lv_obj_move_foreground(qrBackdrop);lv_obj_move_foreground(qrCanvas);lv_obj_move_foreground(accessLabel);}
static void armWeb(lv_event_t*){if(test_mode::enabled){if(WiFi.status()!=WL_CONNECTED){lv_label_set_text(accessLabel,"TEST MODE - Wi-Fi is not connected");lv_obj_clear_flag(accessLabel,LV_OBJ_FLAG_HIDDEN);return;}String url="http://"+String(test_mode::mdnsName)+".local/";presentQr(url,"Scan to open "+url+" - tap screen to close");return;}stopWeb();accessGate.arm(millis());apSsid="Kia-HUD-"+randomSecret(4);apPassword=randomSecret(20);WiFi.mode(cfg.ssid.length()?WIFI_AP_STA:WIFI_AP);WiFi.softAP(apSsid.c_str(),apPassword.c_str(),1,0,1);dns.start(53,"*",WiFi.softAPIP());presentQr("WIFI:T:WPA;S:"+apSsid+";P:"+apPassword+";;","Scan to join "+apSsid+" - tap screen to close");}
static void initDisplay(){
  if(!display.begin()){Serial.println("Display/touch initialization failed");return;}
  lv_obj_set_style_bg_color(lv_scr_act(),lv_color_hex(0x071018),0);dashboard.setWebAccessCallback(armWeb);dashboard.setBeeperCallback(triggerBeeper);dashboard.begin(displayCfg);
  armButton=lv_obj_create(lv_scr_act());lv_obj_set_pos(armButton,0,0);lv_obj_set_size(armButton,480,480);lv_obj_set_style_bg_opa(armButton,LV_OPA_TRANSP,0);lv_obj_set_style_border_width(armButton,0,0);lv_obj_set_style_pad_all(armButton,0,0);lv_obj_set_style_radius(armButton,0,0);lv_obj_add_flag(armButton,LV_OBJ_FLAG_CLICKABLE);lv_obj_clear_flag(armButton,LV_OBJ_FLAG_SCROLLABLE);lv_obj_add_event_cb(armButton,armWeb,LV_EVENT_CLICKED,nullptr);
  qrBackdrop=lv_obj_create(lv_scr_act());lv_obj_set_pos(qrBackdrop,0,0);lv_obj_set_size(qrBackdrop,480,480);lv_obj_set_style_bg_color(qrBackdrop,lv_color_black(),0);lv_obj_set_style_bg_opa(qrBackdrop,LV_OPA_COVER,0);lv_obj_set_style_border_width(qrBackdrop,0,0);lv_obj_set_style_radius(qrBackdrop,0,0);lv_obj_add_flag(qrBackdrop,LV_OBJ_FLAG_HIDDEN|LV_OBJ_FLAG_CLICKABLE);lv_obj_clear_flag(qrBackdrop,LV_OBJ_FLAG_SCROLLABLE);lv_obj_add_event_cb(qrBackdrop,hideQr,LV_EVENT_CLICKED,nullptr);
  qrCanvas=lv_canvas_create(lv_scr_act());lv_obj_align(qrCanvas,LV_ALIGN_CENTER,0,-12);lv_obj_add_flag(qrCanvas,LV_OBJ_FLAG_HIDDEN|LV_OBJ_FLAG_CLICKABLE);lv_obj_add_event_cb(qrCanvas,hideQr,LV_EVENT_CLICKED,nullptr);
  accessLabel=lv_label_create(lv_scr_act());lv_obj_set_style_text_align(accessLabel,LV_TEXT_ALIGN_CENTER,0);lv_obj_set_style_text_color(accessLabel,lv_color_hex(0xffcb67),0);lv_obj_align(accessLabel,LV_ALIGN_BOTTOM_MID,0,-5);lv_obj_add_flag(accessLabel,LV_OBJ_FLAG_HIDDEN);
  dashboard.sendToBack();display.setBrightness(cfg.brightness);
}
static void initWifi(){WiFi.mode(WIFI_STA);WiFi.setHostname(test_mode::enabled?test_mode::mdnsName:cfg.hostname.c_str());setenv("TZ","CET-1CEST,M3.5.0,M10.5.0/3",1);tzset();configTime(0,0,"pool.ntp.org","time.cloudflare.com");if(test_mode::enabled)WiFi.begin(test_mode::ssid,test_mode::password);else if(cfg.ssid.length())WiFi.begin(cfg.ssid,cfg.password);else WiFi.disconnect(false,false);}
static void updateTestNetwork(){if(!displayStarted||!accessLabel||otaConnecting||otaStarted||!test_mode::enabled||WiFi.status()!=WL_CONNECTED)return;if(!mdnsStarted){mdnsStarted=MDNS.begin(test_mode::mdnsName);if(mdnsStarted)MDNS.addService("http","tcp",80);}static IPAddress shown;if(shown!=WiFi.localIP()||lv_obj_has_flag(accessLabel,LV_OBJ_FLAG_HIDDEN)){shown=WiFi.localIP();lv_label_set_text_fmt(accessLabel,"TEST MODE - LAN access\nhttp://%s.local\nhttp://%s",test_mode::mdnsName,shown.toString().c_str());lv_obj_clear_flag(accessLabel,LV_OBJ_FLAG_HIDDEN);}}
static void sendFrameExport(AsyncWebServerRequest*r,bool csv){size_t snapshotHead=frameHead,snapshotCount=frameCount,snapshotCapacity=frameCapacity;auto response=r->beginChunkedResponse(csv?"text/csv":"text/plain",[snapshotHead,snapshotCount,snapshotCapacity,cursor=(size_t)0,csv](uint8_t*buffer,size_t maximum,size_t index)mutable->size_t{size_t used=0;if(csv&&index==0){const char*header="seconds,milliseconds,id,dlc,data,decode\r\n";size_t length=strlen(header);if(length>maximum)return 0;memcpy(buffer,header,length);used=length;}while(cursor<snapshotCount){CanFrame f=frames[(snapshotHead+snapshotCapacity-snapshotCount+cursor)%snapshotCapacity];char row[192],raw[25]={};for(int i=0;i<f.dlc;i++)snprintf(raw+strlen(raw),sizeof(raw)-strlen(raw),"%02X%s",f.data[i],i+1<f.dlc?(csv?" ":""):"");int length;if(csv){auto decoded=obdDescription(f);length=snprintf(row,sizeof(row),"%.3f,%u,%03X,%u,\"%s\",\"%s\"\r\n",f.ms/1000.0,f.ms,(unsigned)f.id,f.dlc,raw,decoded.c_str());}else length=snprintf(row,sizeof(row),"(%u.%03u000) can0 %03X#%s\n",f.ms/1000,f.ms%1000,(unsigned)f.id,raw);if(length<=0||(size_t)length>maximum-used)break;memcpy(buffer+used,row,length);used+=length;cursor++;}return used;});response->addHeader("Content-Disposition",csv?"attachment; filename=kia-hud-2min.csv":"attachment; filename=kia-hud-2min.log");response->addHeader("Cache-Control","no-store");r->send(response);}
static void appendFrameSummary(JsonObject o,const FrameTypeStats&type,const FrameTypeSummary&summary){o["key"]=type.key;o["name"]=(type.latest.id>=0x7E8&&type.latest.id<=0x7EF&&type.latest.dlc>=3)?obdPidName(type.latest.data[2]):"CAN frame";o["count"]=summary.count;o["frequency"]=(summary.count>1&&summary.lastMs>summary.firstMs)?(summary.count-1)*1000.0f/(summary.lastMs-summary.firstMs):0;o["value"]=summary.metric?summary.latest:0;o["min"]=summary.metric?summary.minimum:0;o["max"]=summary.metric?summary.maximum:0;o["realMin"]=type.realMin;o["realMax"]=type.realMax;o["unit"]=type.unit;o["metric"]=summary.metric;char raw[25]={};for(int i=0;i<type.latest.dlc;i++)snprintf(raw+strlen(raw),sizeof(raw)-strlen(raw),"%02X%s",type.latest.data[i],i+1<type.latest.dlc?" ":"");o["raw"]=raw;}
static void sendFrameTypes(AsyncWebServerRequest*r){performance->webBegin(r);uint32_t started=micros();JsonDocument j;auto out=j.to<JsonArray>();uint32_t now=millis();if(frameAnalytics&&frameAnalyticsMutex&&xSemaphoreTake(frameAnalyticsMutex,pdMS_TO_TICKS(10))==pdTRUE){for(size_t i=0;i<FRAME_TYPE_CAPACITY;i++){const auto&type=frameAnalytics->data()[i];if(!type.used)continue;auto summary=frameAnalytics->summarize(type,now);if(summary.count)appendFrameSummary(out.add<JsonObject>(),type,summary);}xSemaphoreGive(frameAnalyticsMutex);}performance->recordAnalysis(micros()-started);sendJson(r,j);}
static void sendFrameDetail(AsyncWebServerRequest*r,const char*key){performance->webBegin(r);uint32_t started=micros();JsonDocument j;uint32_t now=millis();bool found=false;if(frameAnalytics&&frameAnalyticsMutex&&xSemaphoreTake(frameAnalyticsMutex,pdMS_TO_TICKS(10))==pdTRUE){const auto*type=frameAnalytics->find(key);if(type){auto summary=frameAnalytics->summarize(*type,now);if(summary.count){found=true;appendFrameSummary(j.to<JsonObject>(),*type,summary);j["description"]=obdDescription(type->latest);j["windowMs"]=summary.count>1?summary.lastMs-summary.firstMs:0;j["lastChangeMs"]=type->lastChangeMs;j["changeAgeMs"]=type->lastChangeMs?now-type->lastChangeMs:0;auto history=j["history"].to<JsonArray>();uint32_t nowSecond=now/1000;for(int age=(int)FRAME_HISTORY_BUCKETS-1;age>=0;age--){if(nowSecond<(uint32_t)age)continue;uint32_t second=nowSecond-age;const auto&bucket=type->buckets[second%FRAME_HISTORY_BUCKETS];if(bucket.second==second&&bucket.metric){auto point=history.add<JsonObject>();point["ms"]=bucket.lastMs;point["value"]=bucket.latest;}}}}xSemaphoreGive(frameAnalyticsMutex);}performance->recordAnalysis(micros()-started);if(!found){r->send(404,"application/json","{\"error\":\"frame type not found\"}");performance->webEnd(r);return;}sendJson(r,j);}
static void analysisRoutes(){
  server.on("/api/performance",HTTP_GET,[](AsyncWebServerRequest*r){if(!auth(r))return;JsonDocument j;performance->toJson(j);sendJson(r,j);});
  server.on("/api/screenshot.rgb565",HTTP_GET,[](AsyncWebServerRequest*r){if(!auth(r))return;auto response=r->beginResponse("application/octet-stream",DisplayPort::SCREENSHOT_BYTES,[](uint8_t*buffer,size_t maximum,size_t index){return display.readScreenshot(buffer,maximum,index);});response->addHeader("X-Framebuffer-Width","480");response->addHeader("X-Framebuffer-Height","480");response->addHeader("X-Pixel-Format","RGB565-LE");response->addHeader("Cache-Control","no-store");r->send(response);});
  server.on("/api/can-status",HTTP_GET,[](AsyncWebServerRequest*r){if(!auth(r))return;JsonDocument j;j["frameTotal"]=frameTotal;j["ageMs"]=millis()-telemetry.lastCanMs;j["targetFps"]=cfg.simulateObd?SIMULATED_CAN_FPS:0;sendJson(r,j);});
  server.on("/api/pids",HTTP_GET,[](AsyncWebServerRequest*r){if(!auth(r))return;JsonDocument j;auto a=j.to<JsonArray>();for(const auto&d:SAE_PIDS){auto o=a.add<JsonObject>();char pid[3];snprintf(pid,sizeof(pid),"%02X",d.pid);o["pid"]=pid;o["name"]=d.name;o["unit"]=d.unit;o["min"]=d.minimum;o["max"]=d.maximum;o["bytes"]=d.bytes;bool seen=false,supported=false;for(size_t n=0;n<frameCount;n++){auto&f=frames[(frameHead+frameCapacity-frameCount+n)%frameCapacity];if(f.id<0x7E8||f.id>0x7EF||f.dlc<4||f.data[1]!=0x41)continue;if(f.data[2]==d.pid)seen=true;if((f.data[2]%0x20)==0&&f.dlc>=7&&d.pid>f.data[2]&&d.pid<=f.data[2]+32){uint8_t bit=d.pid-f.data[2]-1;supported|=(f.data[3+bit/8]&(0x80>>(bit%8)))!=0;}}o["seen"]=seen;o["supported"]=supported;}sendJson(r,j);});
  server.on("/api/ecus",HTTP_GET,[](AsyncWebServerRequest*r){if(!auth(r))return;JsonDocument j;auto a=j.to<JsonArray>();for(uint32_t id=0x7E8;id<=0x7EF;id++){uint32_t count=0,last=0;bool pids[256]={};for(size_t n=0;n<frameCount;n++){auto&f=frames[(frameHead+frameCapacity-frameCount+n)%frameCapacity];if(f.id!=id)continue;count++;last=f.ms;if(f.dlc>=3&&f.data[1]==0x41)pids[f.data[2]]=true;}if(!count)continue;auto o=a.add<JsonObject>();char name[8];snprintf(name,sizeof(name),"ECU %03X",(unsigned)id);o["id"]=id;o["name"]=name;o["frames"]=count;o["lastMs"]=last;auto pa=o["pids"].to<JsonArray>();for(int p=0;p<256;p++)if(pids[p])pa.add(p);}sendJson(r,j);});
  server.on("/api/isotp",HTTP_GET,[](AsyncWebServerRequest*r){if(!auth(r))return;JsonDocument j;auto a=j.to<JsonArray>();uint8_t payload[256];for(size_t n=0;n<frameCount;n++){auto&f=frames[(frameHead+frameCapacity-frameCount+n)%frameCapacity];if(f.dlc<2||(f.data[0]>>4)!=1)continue;uint16_t total=((f.data[0]&15)<<8)|f.data[1],used=0;for(int i=2;i<f.dlc&&used<total;i++)payload[used++]=f.data[i];uint8_t seq=1;for(size_t m=n+1;m<frameCount&&used<total;m++){auto&c=frames[(frameHead+frameCapacity-frameCount+m)%frameCapacity];if(c.id!=f.id||c.dlc<2||(c.data[0]>>4)!=2||(c.data[0]&15)!=(seq&15))continue;for(int i=1;i<c.dlc&&used<total;i++)payload[used++]=c.data[i];seq++;}auto o=a.add<JsonObject>();char id[9],raw[513]={};snprintf(id,sizeof(id),"%03X",(unsigned)f.id);for(int i=0;i<used;i++)snprintf(raw+strlen(raw),sizeof(raw)-strlen(raw),"%02X",payload[i]);o["id"]=id;o["expected"]=total;o["received"]=used;o["complete"]=used==total;o["payload"]=raw;}sendJson(r,j);});
  server.on("/api/diagnostics",HTTP_GET,[](AsyncWebServerRequest*r){if(!auth(r))return;JsonDocument j;auto a=j.to<JsonArray>();for(size_t n=0;n<frameCount;n++){auto&f=frames[(frameHead+frameCapacity-frameCount+n)%frameCapacity];if(f.id<0x7E8||f.id>0x7EF||f.dlc<4)continue;uint8_t mode=f.data[1];if(mode!=0x42&&mode!=0x43&&mode!=0x47&&mode!=0x4A)continue;for(int i=2;i+1<f.dlc;i+=2){if(!f.data[i]&&!f.data[i+1])continue;static const char family[]="PCBU";char dtc[8];snprintf(dtc,sizeof(dtc),"%c%01X%02X",family[f.data[i]>>6],(f.data[i]>>4)&3,((f.data[i]&15)<<8)|f.data[i+1]);auto o=a.add<JsonObject>();o["dtc"]=dtc;o["ecu"]=f.id;o["kind"]=mode==0x42?"freeze-frame":mode==0x43?"stored":mode==0x47?"pending":"permanent";o["ms"]=f.ms;}}sendJson(r,j);});
  server.on("/api/export.csv",HTTP_GET,[](AsyncWebServerRequest*r){if(!auth(r))return;sendFrameExport(r,true);});
  server.on("/api/export.log",HTTP_GET,[](AsyncWebServerRequest*r){if(!auth(r))return;sendFrameExport(r,false);});
}
static void routes(){
  analysisRoutes();
  events.onConnect([](AsyncEventSourceClient*client){client->send("connected","ready",millis(),1000);});server.addHandler(&events);
  server.on("/",HTTP_GET,[](AsyncWebServerRequest*r){uint32_t id=clientId(r);if(!fromTestLan(r)&&!accessGate.authorized(millis(),id)&&!accessGate.claim(millis(),id)){r->send(403,"text/plain","Touch Web access on the HUD and scan its QR code.");return;}r->send_P(200,"text/html",WEB_UI);});
  server.on("/app.css",HTTP_GET,[](AsyncWebServerRequest*r){if(!auth(r))return;r->send_P(200,"text/css",WEB_CSS);});
  server.on("/runtime.js",HTTP_GET,[](AsyncWebServerRequest*r){if(!auth(r))return;r->send_P(200,"application/javascript",WEB_RUNTIME_JS);});
  server.on("/app.js",HTTP_GET,[](AsyncWebServerRequest*r){if(!auth(r))return;r->send_P(200,"application/javascript",WEB_APP_JS);});
  server.on("/analysis.js",HTTP_GET,[](AsyncWebServerRequest*r){if(!auth(r))return;r->send_P(200,"application/javascript",ANALYSIS_JS);});
  server.on("/features.js",HTTP_GET,[](AsyncWebServerRequest*r){if(!auth(r))return;r->send_P(200,"application/javascript",WEB_FEATURES_JS);});
  server.on("/generate_204",HTTP_GET,[](AsyncWebServerRequest*r){r->redirect("/");});server.on("/hotspot-detect.html",HTTP_GET,[](AsyncWebServerRequest*r){r->redirect("/");});server.on("/connecttest.txt",HTTP_GET,[](AsyncWebServerRequest*r){r->redirect("/");});server.on("/ncsi.txt",HTTP_GET,[](AsyncWebServerRequest*r){r->redirect("/");});
  server.on("/api/compatibility",HTTP_GET,[](AsyncWebServerRequest*r){if(!auth(r))return;JsonDocument j;j["firmwareVersion"]=FIRMWARE_VERSION;j["uiVersion"]=FIRMWARE_VERSION;j["apiVersion"]=2;j["configSchemaVersion"]=CONFIG_SCHEMA_VERSION;j["activeDisplay"]=activeVirtualDisplay<0?"main":cfg.virtualDisplays[activeVirtualDisplay].id;auto c=j["capabilities"].to<JsonArray>();c.add("event-stream");c.add("virtual-displays");c.add("asset-storage");c.add("file-manager");c.add("ui-diagnostics");sendJson(r,j);});
  server.on("/api/storage",HTTP_GET,[](AsyncWebServerRequest*r){if(!auth(r))return;JsonDocument j;j["mounted"]=boardServices.sdMounted();j["writable"]=boardServices.sdWritable();j["stage"]=boardServices.sdStage();j["attempts"]=boardServices.sdAttempts();j["frequencyKhz"]=boardServices.sdFrequencyKhz();j["cardTypeRaw"]=boardServices.sdCardType();j["cardSizeBytes"]=boardServices.sdCardSize();j["usedBytes"]=boardServices.sdMounted()?SD_MMC.usedBytes():0;j["pins"]["clk"]=2;j["pins"]["cmd"]=1;j["pins"]["d0"]=4;j["busWidth"]=1;j["batteryController"]=boardServices.batteryPresent();j["batteryStatusRaw"]=boardServices.batteryStatus();j["batteryPower"]=batteryPowerActive;j["buzzer"]=boardServices.buzzerPresent();sendJson(r,j);});
  server.on("/api/files",HTTP_GET,[](AsyncWebServerRequest*r){if(!auth(r))return;if(!boardServices.sdMounted()){sdError(r,503,"TF card unavailable");return;}String path;if(!sdPath(r->hasParam("path")?r->getParam("path")->value():"/",path)){sdError(r,400,"invalid path");return;}File directory=SD_MMC.open(path);if(!directory||!directory.isDirectory()){if(directory)directory.close();sdError(r,404,"directory not found");return;}JsonDocument j;j["path"]=path;j["totalBytes"]=boardServices.sdCardSize();j["usedBytes"]=SD_MMC.usedBytes();j["writable"]=boardServices.sdWritable();auto entries=j["entries"].to<JsonArray>();for(File file=directory.openNextFile();file;file=directory.openNextFile()){auto item=entries.add<JsonObject>();String full=file.path();item["name"]=sdBaseName(full);item["path"]=full;item["directory"]=file.isDirectory();item["size"]=file.isDirectory()?0:file.size();file.close();}directory.close();sendJson(r,j);});
  server.on("/api/file-download",HTTP_GET,[](AsyncWebServerRequest*r){if(!auth(r))return;if(!boardServices.sdMounted()){sdError(r,503,"TF card unavailable");return;}String path;if(!r->hasParam("path")||!sdPath(r->getParam("path")->value(),path,false)){sdError(r,400,"invalid path");return;}File file=SD_MMC.open(path);if(!file||file.isDirectory()){if(file)file.close();sdError(r,404,"file not found");return;}file.close();auto response=r->beginResponse(SD_MMC,path,"application/octet-stream",true);response->addHeader("Cache-Control","no-store");r->send(response);performance->webEnd(r);});
  server.on("/api/files/mkdir",HTTP_POST,[](AsyncWebServerRequest*r){if(!auth(r))return;if(!boardServices.sdWritable()){sdError(r,503,"TF card is not writable");return;}String path;if(!r->hasParam("path")||!sdPath(r->getParam("path")->value(),path,false)){sdError(r,400,"invalid path");return;}if(SD_MMC.exists(path)){sdError(r,409,"path already exists");return;}if(!SD_MMC.mkdir(path)){sdError(r,500,"could not create directory");return;}r->send(201,"application/json","{\"created\":true}");performance->webEnd(r);});
  server.on("/api/files/rename",HTTP_POST,[](AsyncWebServerRequest*r){if(!auth(r))return;if(!boardServices.sdWritable()){sdError(r,503,"TF card is not writable");return;}String from,to;if(!r->hasParam("path")||!r->hasParam("to")||!sdPath(r->getParam("path")->value(),from,false)||!sdPath(r->getParam("to")->value(),to,false)){sdError(r,400,"invalid path");return;}if(!SD_MMC.exists(from)){sdError(r,404,"source not found");return;}if(SD_MMC.exists(to)){sdError(r,409,"destination already exists");return;}if(!SD_MMC.rename(from,to)){sdError(r,500,"rename failed");return;}r->send(200,"application/json","{\"renamed\":true}");performance->webEnd(r);});
  server.on("/api/files",HTTP_DELETE,[](AsyncWebServerRequest*r){if(!auth(r))return;if(!boardServices.sdWritable()){sdError(r,503,"TF card is not writable");return;}String path;if(!r->hasParam("path")||!sdPath(r->getParam("path")->value(),path,false)){sdError(r,400,"invalid path");return;}File file=SD_MMC.open(path);if(!file){sdError(r,404,"path not found");return;}bool directory=file.isDirectory();if(directory&&file.openNextFile()){file.close();sdError(r,409,"directory is not empty");return;}file.close();bool removed=directory?SD_MMC.rmdir(path):SD_MMC.remove(path);if(!removed){sdError(r,500,"delete failed");return;}r->send(200,"application/json","{\"deleted\":true}");performance->webEnd(r);});
  server.on("/api/files/upload",HTTP_POST,[](AsyncWebServerRequest*r){if(!auth(r))return;String*path=(String*)r->_tempObject;bool uploaded=path&&SD_MMC.exists(*path);JsonDocument j;j["uploaded"]=uploaded;j["path"]=uploaded?*path:"";String body;serializeJson(j,body);delete path;r->_tempObject=nullptr;r->send(uploaded?201:500,"application/json",body);performance->webEnd(r);},[](AsyncWebServerRequest*r,String filename,size_t index,uint8_t*data,size_t len,bool final){if(!requestAuthorized(r)||!boardServices.sdWritable())return;if(!index){String directory=r->hasParam("path")?r->getParam("path")->value():"/",safeDirectory;filename.replace("\\","_");filename.replace("/","_");filename.replace("..","_");filename.trim();String path;if(!filename.length()||!sdPath(directory,safeDirectory)||!sdPath(safeDirectory+(safeDirectory=="/"?"":"/")+filename,path,false))return;r->_tempObject=new String(path);r->_tempFile=SD_MMC.open(path,FILE_WRITE);}if(r->_tempFile)r->_tempFile.write(data,len);if(final&&r->_tempFile)r->_tempFile.close();});
  server.on("/api/resources",HTTP_GET,[](AsyncWebServerRequest*r){if(!auth(r))return;JsonDocument j;auto a=j["resources"].to<JsonArray>();if(boardServices.sdMounted()){for(const char*folder:{"/hud/graphics","/hud/icons"}){File dir=SD_MMC.open(folder);if(!dir)continue;for(File f=dir.openNextFile();f;f=dir.openNextFile())if(!f.isDirectory()){String path=f.path();if(path.endsWith(".rgb565")){auto item=a.add<JsonObject>();item["path"]=path;item["name"]=sdBaseName(path);}}dir.close();}}sendJson(r,j);});
  server.on("/api/resources/upload",HTTP_POST,[](AsyncWebServerRequest*r){if(!auth(r))return;if(!boardServices.sdWritable()){r->send(503,"application/json","{\"error\":\"TF card unavailable or read-only\"}");return;}String*path=(String*)r->_tempObject;bool uploaded=path&&SD_MMC.exists(*path);JsonDocument j;j["uploaded"]=uploaded;j["path"]=uploaded?*path:"";String response;serializeJson(j,response);delete path;r->_tempObject=nullptr;r->send(uploaded?201:500,"application/json",response);},[](AsyncWebServerRequest*r,String filename,size_t index,uint8_t*data,size_t len,bool final){if(!requestAuthorized(r)||!boardServices.sdWritable())return;filename.replace("\\","_");filename.replace("/","_");filename.replace("..","_");if(!filename.endsWith(".rgb565"))filename+=".rgb565";String path="/hud/graphics/"+filename;if(!index){r->_tempObject=new String(path);r->_tempFile=SD_MMC.open(path,FILE_WRITE);}if(r->_tempFile)r->_tempFile.write(data,len);if(final&&r->_tempFile)r->_tempFile.close();});
  server.on("/api/status",HTTP_GET,[](AsyncWebServerRequest*r){if(!auth(r))return;JsonDocument j;j["version"]=FIRMWARE_VERSION;time_t now=time(nullptr);char date[40]="Not synchronized";if(now>1700000000){struct tm local;localtime_r(&now,&local);strftime(date,sizeof(date),"%Y-%m-%d %H:%M:%S %Z",&local);}j["date"]=date;j["uptime"]=millis()/1000;j["heap"]=ESP.getFreeHeap();j["minHeap"]=ESP.getMinFreeHeap();j["psramFree"]=ESP.getFreePsram();j["flashSize"]=ESP.getFlashChipSize();j["cpuMHz"]=ESP.getCpuFreqMHz();j["sdk"]=ESP.getSdkVersion();j["sdMounted"]=boardServices.sdMounted();j["sdWritable"]=boardServices.sdWritable();j["sdStage"]=boardServices.sdStage();j["sdAttempts"]=boardServices.sdAttempts();j["sdFrequencyKhz"]=boardServices.sdFrequencyKhz();j["client"]=r->client()->remoteIP().toString();j["ip"]=WiFi.localIP().toString();j["rssi"]=WiFi.RSSI();j["canAge"]=(micros()-telemetry.lastCanUs)/1000.0f;j["frameCount"]=frameCount;j["frameCapacity"]=frameCapacity;j["frameHistoryMs"]=frameCount>1?frameAt(frameCount-1).ms-frameAt(0).ms:0;j["displayConfigRequested"]=displayConfigRequested;j["displayConfigApplied"]=displayConfigApplied;j["simulateObd"]=cfg.simulateObd;j["listenOnly"]=cfg.canListenOnly;j["speed"]=telemetry.speedKph;j["rpm"]=telemetry.rpm;j["soc"]=telemetry.soc;j["coolant"]=telemetry.coolantC;j["load"]=telemetry.engineLoad;j["trip"]=telemetry.tripKm;j["gps"]=telemetry.gpsFix;sendJson(r,j);});
  server.on("/ota-config",HTTP_GET,[](AsyncWebServerRequest*r){if(!auth(r))return;r->send_P(200,"text/html",OTA_CONFIG_UI);});
  server.on("/api/ota-start",HTTP_POST,[](AsyncWebServerRequest*r){if(!auth(r))return;if(otaConnecting||otaStarted){r->send(409,"application/json","{\"error\":\"OTA already active\"}");return;}otaStartRequested=true;r->send(202,"application/json","{\"starting\":true}");});
  server.on("/ota-config",HTTP_POST,[](AsyncWebServerRequest*r){if(!auth(r))return;if(!r->hasParam("ssid",true)){r->send(400,"text/plain","SSID required");return;}String ssid=r->getParam("ssid",true)->value();String password=r->hasParam("password",true)?r->getParam("password",true)->value():"";if(ssid.length()>32||(!password.isEmpty()&&(password.length()<8||password.length()>63))){r->send(400,"text/plain","Invalid SSID or password length");return;}cfg.otaSsid=ssid;if(password.length())cfg.otaPassword=password;if(!cfg.save()){r->send(500,"text/plain","Save failed");return;}r->send(200,"text/html","<h2>Hotspot saved</h2><p>Return to Configuration and select Start OTA update.</p><a href='/'>Back</a>");});
  server.on("/api/config",HTTP_GET,[](AsyncWebServerRequest*r){if(!auth(r))return;String s;cfg.toJson(s);r->send(200,"application/json",s);});
  server.on("/api/display-config",HTTP_GET,[](AsyncWebServerRequest*r){if(!auth(r))return;JsonDocument j;j["brightness"]=displayCfg.brightness;j["simulateObd"]=displayCfg.simulateObd;j["canListenOnly"]=displayCfg.canListenOnly;Config::widgetsToJson(j["widgets"].to<JsonArray>(),displayCfg.widgets);String s;serializeJson(j,s);r->send(200,"application/json",s);});
  server.on("/api/config",HTTP_PUT,[](AsyncWebServerRequest*r){},nullptr,[](AsyncWebServerRequest*r,uint8_t*d,size_t n,size_t index,size_t total){if(index==0){if(!auth(r))return;r->_tempObject=new String();((String*)r->_tempObject)->reserve(total);}auto body=(String*)r->_tempObject;if(!body)return;body->concat((const char*)d,n);if(index+n<total)return;Config*candidate=(Config*)heap_caps_malloc(sizeof(Config),MALLOC_CAP_SPIRAM);if(!candidate){delete body;r->_tempObject=nullptr;r->send(503,"application/json","{\"error\":\"configuration memory unavailable\"}");return;}xSemaphoreTake(configMutex,portMAX_DELAY);new(candidate)Config(cfg);uint32_t oldFingerprint=activeDisplayFingerprint(cfg);xSemaphoreGive(configMutex);bool parsed=candidate->fromJson(*body),stored=parsed&&candidate->save();uint32_t revision=0;if(stored){xSemaphoreTake(configMutex,portMAX_DELAY);uint32_t newFingerprint=activeDisplayFingerprint(*candidate);cfg=*candidate;if(oldFingerprint!=newFingerprint)++displayConfigRequested;revision=displayConfigRequested;splashCacheRefreshRequested=true;xSemaphoreGive(configMutex);}candidate->~Config();free(candidate);delete body;r->_tempObject=nullptr;if(!parsed){r->send(400,"application/json","{\"error\":\"config parse failed\"}");return;}if(!stored){r->send(500,"application/json","{\"error\":\"config storage failed\"}");return;}char response[64];snprintf(response,sizeof(response),"{\"saved\":true,\"displayRevision\":%u}",(unsigned)revision);r->send(200,"application/json",response);events.send(response,"config-saved",millis());});
  server.on("/api/frames",HTTP_GET,[](AsyncWebServerRequest*r){if(!auth(r))return;performance->webBegin(r);String q=r->hasParam("q")?r->getParam("q")->value():"";JsonDocument j;auto a=j.to<JsonArray>();size_t start=frameCount>100?frameCount-100:0;for(size_t k=start;k<frameCount;k++){auto&f=frameAt(k);std::string decoded=obdDescription(f);String decodedText=decoded.c_str();if(!frameMatches(f,q.c_str())&&!decodedText.equalsIgnoreCase(q)&&decodedText.indexOf(q)<0)continue;auto o=a.add<JsonObject>();char id[9],bytes[25]={};snprintf(id,sizeof(id),"%03X",(unsigned)f.id);for(int i=0;i<f.dlc;i++)snprintf(bytes+strlen(bytes),sizeof(bytes)-strlen(bytes),"%02X%s",f.data[i],i+1<f.dlc?" ":"");o["ms"]=f.ms;o["id"]=id;o["data"]=bytes;if(!decoded.empty())o["decode"]=decoded;}sendJson(r,j);});
  server.on("/api/frame-types",HTTP_GET,[](AsyncWebServerRequest*r){if(!auth(r))return;sendFrameTypes(r);});
  server.on("/api/frame-detail",HTTP_GET,[](AsyncWebServerRequest*r){if(!auth(r))return;if(!r->hasParam("key")){r->send(400,"application/json","{\"error\":\"key required\"}");performance->webEnd(r);return;}sendFrameDetail(r,r->getParam("key")->value().c_str());});
  server.on("/api/logout",HTTP_POST,[](AsyncWebServerRequest*r){if(!auth(r))return;r->send(204);if(!fromTestLan(r))stopWebRequested=true;});server.onNotFound([](AsyncWebServerRequest*r){if(fromTestLan(r)||accessGate.joinable(millis())||accessGate.authorized(millis(),clientId(r)))r->redirect("/");else r->send(404,"text/plain","Web access inactive");});server.begin();
}
void setup(){
  Serial.begin(115200);delay(100);performance=new PerformanceMonitor();Serial.printf("Kia XCeed HUD v%s booting\n",FIRMWARE_VERSION);
  cfgStorage=(Config*)heap_caps_malloc(sizeof(Config),MALLOC_CAP_SPIRAM);
  if(!cfgStorage){Serial.printf("FATAL: PSRAM Config allocation failed (%u bytes)\n",(unsigned)sizeof(Config));return;}
  new(cfgStorage) Config();
  Serial.printf("Config allocated in PSRAM (%u bytes); largest DMA block %u\n",(unsigned)sizeof(Config),(unsigned)heap_caps_get_largest_free_block(MALLOC_CAP_DMA));
  frameCapacity=FRAME_HISTORY_CAPACITY;while(frameCapacity>=30000&&!frames){frames=(CanFrame*)heap_caps_malloc(frameCapacity*sizeof(CanFrame),MALLOC_CAP_SPIRAM);if(!frames)frameCapacity/=2;}Serial.printf("CAN history allocated in PSRAM: %u frames, %u bytes, target %.0f seconds at %u fps\n",(unsigned)frameCapacity,(unsigned)(frameCapacity*sizeof(CanFrame)),frameCapacity/(float)SIMULATED_CAN_FPS,(unsigned)SIMULATED_CAN_FPS);
  configMutex=xSemaphoreCreateMutex();
  cfg.load();bootDisplayUntil=millis()+cfg.virtualDisplays[0].timeoutMs;if(cfg.virtualDisplays[0].enabled)activeVirtualDisplay=0;selectDisplay(activeVirtualDisplay);Serial.printf("Config schema %u loaded\n",CONFIG_SCHEMA_VERSION);
  displayStarted=true;initDisplay();displayConfigApplied=displayConfigRequested;Serial.println("Display and touch initialized");
  Serial.println("Board services initialization deferred until network startup completes");
  initWifi();Serial.println("Wi-Fi stack initialized; temporary AP inactive");
  routes();Serial.println("Web service ready; touch Web access to arm");
  Serial.printf("CAN %s\n",bus.begin(cfg.canListenOnly,cfg.canRate)?"initialized":"initialization failed");
  performance->begin();Serial.println("Performance monitor initialized");
}
void loop() {
  uint32_t loopStarted=micros();
  static bool frameAnalyticsStarted=false;if(!frameAnalyticsStarted&&millis()>=1000&&(WiFi.status()==WL_CONNECTED||millis()>=10000)){frameAnalyticsStarted=true;frameAnalytics=(FrameAnalytics*)heap_caps_calloc(1,sizeof(FrameAnalytics),MALLOC_CAP_SPIRAM);if(frameAnalytics)new(frameAnalytics)FrameAnalytics();frameAnalyticsMutex=xSemaphoreCreateMutex();Serial.printf("Frame analytics %s (%u bytes, %u types, %u one-second buckets)\n",frameAnalytics?"allocated in PSRAM":"unavailable",(unsigned)sizeof(FrameAnalytics),(unsigned)FRAME_TYPE_CAPACITY,(unsigned)FRAME_HISTORY_BUCKETS);}
  static bool boardServicesStarted=false;if(!boardServicesStarted&&millis()>=10000&&(WiFi.status()==WL_CONNECTED||millis()>=30000)){boardServicesStarted=true;xTaskCreatePinnedToCore(initBoardServices,"boardServices",6144,nullptr,1,nullptr,0);Serial.println("Board services initialization started asynchronously");}
  dns.processNextRequest();
  if(otaStartRequested){otaStartRequested=false;startOta(nullptr);}
  updateOta();
  if(boardServicesReady)boardServices.update(millis());batteryPowerActive=boardServicesReady&&boardServices.batteryPresent()&&telemetry.lastCanMs&&millis()-telemetry.lastCanMs>3000;telemetry.batteryPower=batteryPowerActive;
  if(boardServicesReady&&splashCacheRefreshRequested){splashCacheRefreshRequested=false;refreshSplashCache();}
  if(qrShownAt&&millis()-qrShownAt>=60000)hideQr(nullptr);
  int8_t desiredDisplay=desiredVirtualDisplay();
  if(displayConfigApplied!=displayConfigRequested||desiredDisplay!=activeVirtualDisplay){xSemaphoreTake(configMutex,portMAX_DELAY);selectDisplay(desiredDisplay);uint32_t revision=displayConfigRequested;xSemaphoreGive(configMutex);dashboard.rebuild(displayCfg);dashboard.update(displayCfg,telemetry,millis());dashboard.sendToBack();lv_obj_move_foreground(armButton);display.setBrightness(displayCfg.brightness);activeVirtualDisplay=desiredDisplay;displayConfigApplied=revision;Serial.printf("Display revision %u applied; virtual display %d\n",(unsigned)revision,(int)activeVirtualDisplay);}
  updateTestNetwork();
  if(stopWebRequested){stopWebRequested=false;stopWeb();}
  uint32_t canStarted=micros();CanFrame f;
  uint8_t receivedThisLoop=0;while(receivedThisLoop<32&&micros()-canStarted<3000&&bus.receive(f)) {
    if(cfg.simulateObd)continue;
    recordFrame(f);frameTotal++;telemetry.lastCanMs=f.ms;telemetry.lastCanUs=micros();
    decodeObd(f,telemetry);receivedThisLoop++;
  }
  static uint32_t nextSimUs=0,simSequence=0;
  if(cfg.simulateObd){uint32_t nowUs=micros();if(!nextSimUs)nextSimUs=nowUs;uint8_t emitted=0;while((int32_t)(nowUs-nextSimUs)>=0&&emitted<SIMULATED_CAN_MAX_CATCH_UP){f=simulatedFrame(millis(),simSequence++);recordFrame(f);frameTotal++;telemetry.lastCanMs=f.ms;telemetry.lastCanUs=micros();decodeObd(f,telemetry);nextSimUs+=SIMULATED_CAN_PERIOD_US;emitted++;}if((int32_t)(nowUs-nextSimUs)>100000){performance->noteCanDropped((nowUs-nextSimUs)/SIMULATED_CAN_PERIOD_US);nextSimUs=nowUs;}}else nextSimUs=0;
  performance->recordCan(micros()-canStarted);
  static uint32_t lastPid=0; static uint8_t pidIndex=0;
  if(!cfg.simulateObd&&!cfg.canListenOnly && millis()-lastPid>=250) {
    static const uint8_t safePids[]={0x00,0x20,0x40,0x60,0x80,0xA0,0x0D,0x0C,0x05,0x04,0x2F,0x0F,0x10,0x11,0x1F,0x42,0x46,0x5C,0x5E};
    lastPid=millis(); bus.requestPid(safePids[pidIndex++%(sizeof(safePids)/sizeof(safePids[0]))]);
  }
  if(accessGate.active(millis())&&vehicleMoving())stopWeb();
  if(!accessGate.active(millis())&&apPassword.length())stopWeb();
  static uint32_t last=0;
  if(millis()-last>250) {
    last=millis();
    dashboard.update(displayCfg,telemetry,millis());
  }
  if(displayStarted){uint32_t lcdStarted=micros();performance->noteDisplayService(lcdStarted);display.update();performance->recordLcd(micros()-lcdStarted);} delay(2);
  static uint32_t lastMetricsEvent=0,lastFramesEvent=0,lastCanEvent=0,lastPerformanceEvent=0;uint32_t eventNow=millis();
  if(eventNow-lastMetricsEvent>=500){lastMetricsEvent=eventNow;events.send("{}","metrics",eventNow);}
  if(eventNow-lastFramesEvent>=1000){lastFramesEvent=eventNow;events.send("{}","frames",eventNow);}
  if(eventNow-lastCanEvent>=500){lastCanEvent=eventNow;events.send("{}","can",eventNow);}
  if(eventNow-lastPerformanceEvent>=1000){lastPerformanceEvent=eventNow;events.send("{}","performance",eventNow);}
  performance->recordLoop(micros()-loopStarted);performance->tick(millis());
}
