#ifndef LV_CONF_H
#define LV_CONF_H
#define LV_FONT_MONTSERRAT_14 1
#define LV_FONT_MONTSERRAT_18 1
#define LV_FONT_MONTSERRAT_22 1
#define LV_FONT_MONTSERRAT_26 1
#define LV_FONT_MONTSERRAT_30 1
#define LV_FONT_MONTSERRAT_34 1
#define LV_FONT_MONTSERRAT_38 1
#define LV_FONT_MONTSERRAT_42 1
#define LV_FONT_MONTSERRAT_48 1
#define LV_FONT_UNSCII_16 1
#endif
