#!/usr/bin/env python3
"""Generate the Arduino PROGMEM WebAssets header from lintable web sources."""
from __future__ import annotations

import argparse
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
WEB = ROOT / "firmware" / "KiaXCeedHUD" / "web"
OUTPUT = ROOT / "firmware" / "KiaXCeedHUD" / "src" / "WebAssets.generated.h"
ASSETS = (
    ("WEB_INDEX", "index.html", "HUDHTML"),
    ("WEB_CSS", "app.css", "HUDCSS"),
    ("WEB_RUNTIME_JS", "runtime.js", "HUDRUNTIME"),
    ("WEB_APP_JS", "app.js", "HUDAPP"),
    ("ANALYSIS_JS", "analysis.js", "HUDANALYSIS"),
    ("WEB_FEATURES_JS", "features.js", "HUDFEATURES"),
)


def generate() -> str:
    parts = [
        "// Generated by tools/generate_web_assets.py; do not edit.\n",
        "#pragma once\n#include <Arduino.h>\nnamespace hud {\n",
    ]
    for symbol, filename, delimiter in ASSETS:
        content = (WEB / filename).read_text(encoding="utf-8").replace("\r\n", "\n")
        marker = f"){delimiter}\""
        if marker in content:
            raise ValueError(f"{filename} contains reserved raw-string marker {marker}")
        parts.append(
            f"static const char {symbol}[] PROGMEM=R\"{delimiter}({content}){delimiter}\";\n"
        )
    parts.append("}\n")
    return "".join(parts)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if the generated header is stale")
    args = parser.parse_args()
    rendered = generate()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != rendered:
            print(f"{OUTPUT.relative_to(ROOT)} is stale; run {Path(__file__).name}")
            return 1
        return 0
    OUTPUT.write_text(rendered, encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
