(function(){
"use strict";
labels.icon="Icon / graphic";labels.battery="Backup battery";categories.Graphics=["icon"];if(!categories.System.includes("battery"))categories.System.push("battery");
let activeDisplay="main";
const displayFor=id=>id==="main"?null:(configData.virtualDisplays||[]).find(d=>d.id===id);
function storeDisplay(){let d=displayFor(activeDisplay);if(d)d.widgets=widgets;else configData.widgets=widgets}
function ruleEditor(){let h=$("displayRule"),d=displayFor(activeDisplay);if(!h)return;if(!d){h.innerHTML='<p class="muted">The main display is restored automatically when no enabled rule matches.</p>';return}h.innerHTML=`<label>Name <input id=vdName value="${esc(d.name)}"></label><label><input id=vdEnabled type=checkbox ${d.enabled?'checked':''}> Enabled</label><label>Condition <select id=vdCondition><option value=1>At startup</option><option value=2>Value &gt;</option><option value=3>Value &gt;=</option><option value=4>Value &lt;</option><option value=5>Value &lt;=</option><option value=6>Value =</option><option value=7>Backup battery</option></select></label><label>Metric <select id=vdMetric>${['speed','rpm','soc','coolant','load','canAge','batteryPower'].map(m=>`<option>${m}</option>`).join('')}</select></label><label>Threshold <input id=vdThreshold type=number step=.1 value=${d.threshold||0}></label><label>Timeout <input id=vdTimeout type=number min=0 max=600000 step=250 value=${d.timeoutMs||0}> ms</label>`;$("vdCondition").value=d.condition||2;$("vdMetric").value=d.metric||'speed';h.oninput=()=>{d.name=$("vdName").value;d.enabled=$("vdEnabled").checked;d.condition=+$("vdCondition").value;d.metric=$("vdMetric").value;d.threshold=+$("vdThreshold").value;d.timeoutMs=+$("vdTimeout").value}}
function displayEditor(){if($("virtualDisplayControls")||!configData.virtualDisplays)return;let h=document.createElement('div');h.id='virtualDisplayControls';h.className='card';h.innerHTML=`<h3>Virtual display</h3><label>Editing <select id=activeDisplay><option value=main>${esc(configData.mainDisplayName||'Main')}</option>${configData.virtualDisplays.map(d=>`<option value="${esc(d.id)}">${esc(d.name)}</option>`).join('')}</select></label><div id=displayRule class=grid></div>`;$("display").insertBefore(h,$("display").firstChild);$("activeDisplay").onchange=()=>{storeDisplay();activeDisplay=$("activeDisplay").value;let d=displayFor(activeDisplay);widgets=d?(d.widgets||(d.widgets=[])):configData.widgets;selected=null;edit(null);renderPalette();ruleEditor();draw()};ruleEditor()}
const basePalette=renderPalette;renderPalette=function(){basePalette();let h=$("palette");if(!h||h.querySelector('[data-id=icon]'))return;h.insertAdjacentHTML('beforeend','<div style="width:100%;border-top:1px solid #294052;padding-top:8px"><h4 class=muted style="margin:0 0 6px">Graphics</h4><div class=palette><div class=chip draggable=true data-id=icon>Icon / graphic</div></div></div>');h.querySelector('[data-id=icon]').ondragstart=e=>e.dataTransfer.setData('text/plain','icon')};
const baseDrop=preview.ondrop;preview.ondrop=e=>{if(e.dataTransfer.getData('text/plain')!=='icon')return baseDrop(e);e.preventDefault();if(widgets.length>=40)return;let r=preview.getBoundingClientRect(),w={id:'icon',x:0,y:0,w:120,h:120,visible:true,title:'Icon',resource:'builtin:info',fontSize:18,background:0x102a38,textColor:0xffffff,backgroundOpacity:0,border:false,valueAlign:1,visualStyle:0};w.x=Math.max(0,Math.min(360,Math.round((e.clientX-r.left)*480/r.width-60)));w.y=Math.max(0,Math.min(360,Math.round((e.clientY-r.top)*480/r.height-60)));widgets.push(w);edit(w);renderPalette();draw()};
const baseEdit=edit;edit=function(w){baseEdit(w);if(!w)return;let h=$("editor");if(w.id==='icon'){h.insertAdjacentHTML('beforeend','<fieldset><legend>Graphic</legend><label>Resource <select id=wResource><option value="builtin:info">Information</option><option value="builtin:warning">Warning</option><option value="builtin:temperature">Temperature</option><option value="builtin:battery">Battery</option><option value="builtin:check">Check / OK</option></select></label><label>Upload PNG/JPEG <input id=wResourceUpload type=file accept="image/png,image/jpeg,image/webp"></label><small class=muted>Uploads are converted to RGB565 and stored on the TF card.</small></fieldset>');$("wResource").value=w.resource||'builtin:info';$("wResource").onchange=()=>{w.resource=$("wResource").value;draw()};loadResources(w);$("wResourceUpload").onchange=e=>uploadResource(e.target.files[0],w)}else if(!['text','webAccess','status','time','date','version','mode','wifi','coordinates','gpsLock'].includes(w.id)){h.insertAdjacentHTML('beforeend',`<fieldset><legend>Beeper alert</legend><label><input id=wBeep type=checkbox ${w.beepEnabled?'checked':''}> Enable alert</label><label>When <select id=wBeepWhen><option value=1>Over</option><option value=2>Under</option></select></label><label>Threshold <input id=wBeepThreshold type=number step=.1 value=${w.beepThreshold||0}></label><label>Repeat timeout <input id=wBeepTimeout type=number min=250 max=600000 step=250 value=${w.beepTimeoutMs||5000}> ms</label></fieldset>`);$("wBeepWhen").value=w.beepWhen||1;h.querySelector('fieldset:last-child').oninput=()=>{w.beepEnabled=$("wBeep").checked;w.beepWhen=+$("wBeepWhen").value;w.beepThreshold=+$("wBeepThreshold").value;w.beepTimeoutMs=+$("wBeepTimeout").value}}};
async function loadResources(w){try{let r=await fetch('/api/resources');if(!r.ok||selected!==w)return;let j=await r.json();for(let x of j.resources||[]){if(!x.path.startsWith('/hud/'))continue;let o=document.createElement('option');o.value=x.path;o.textContent=x.name;$("wResource").appendChild(o)}$("wResource").value=w.resource||'builtin:info'}catch(e){console.error('Resource list failed',e)}}
async function uploadResource(file,w){if(!file)return;let image=await createImageBitmap(file),scale=Math.min(1,480/image.width,480/image.height),width=Math.max(1,Math.round(image.width*scale)),height=Math.max(1,Math.round(image.height*scale)),canvas=document.createElement('canvas');canvas.width=width;canvas.height=height;let context=canvas.getContext('2d');context.drawImage(image,0,0,width,height);let rgba=context.getImageData(0,0,width,height).data,bytes=new Uint8Array(4+width*height*2);bytes[0]=width&255;bytes[1]=width>>8;bytes[2]=height&255;bytes[3]=height>>8;for(let s=0,t=4;s<rgba.length;s+=4,t+=2){let p=((rgba[s]&248)<<8)|((rgba[s+1]&252)<<3)|(rgba[s+2]>>3);bytes[t]=p&255;bytes[t+1]=p>>8}let name=file.name.replace(/\.[^.]+$/,'').replace(/[^a-z0-9_-]/gi,'-').slice(0,40)+'.rgb565',body=new FormData();body.append('file',new Blob([bytes]),name);let response=await fetch('/api/resources/upload',{method:'POST',body});if(!response.ok)throw Error(await response.text());let result=await response.json();w.resource=result.path;edit(w);draw()}
const baseSave=saveConfig;saveConfig=function(e){storeDisplay();return baseSave(e)};$("saveLayout").onclick=saveConfig;
const featureValue=value;value=function(w){const rendered=featureValue(w);return w.showUnit===false?rendered.replace(/ (km\/h|rpm|km|%|C|g|ms|us|V|L\/h|dBm)$/,''):rendered};
const featureEdit=edit;edit=function(w){featureEdit(w);if(!w)return;const unitIds=['speed','soc','power','rpm','trip','coolant','load','gpsSpeed','accel','canAge','uptime','intakeTemp','throttle','voltage','ambientTemp','fuelRate','wifiSignal'];if(!unitIds.includes(w.id))return;$("editor").insertAdjacentHTML('beforeend',`<label>Unit <span><input id=wShowUnit type=checkbox ${w.showUnit!==false?'checked':''}> Show unit</span></label>`);$("wShowUnit").oninput=()=>{w.showUnit=$("wShowUnit").checked;draw()}};
let ready=setInterval(()=>{if(!configData?.virtualDisplays)return;clearInterval(ready);displayEditor();renderPalette()},50);
})();
